### ISSUE TITLE
Rendering of SVG broken on IE11+Edge 13.1

### ISSUE THREAD

**Issue by stevekay** [sysstat/sysstat#104]
Unsure whether it's Microsoft's rendering engine or the SVG syntax used by sysstat (perhaps Microsoft code is pedantic and requires strict conformance?).  

Figured worth highlighting this while the SVG aspects are still being developed. 

Chrome 48 (good)
http://i.imgur.com/GdE41Ci.png

Opera 35 (good)
http://i.imgur.com/7cM84Yi.png

Firefox 44 (good)
http://i.imgur.com/GDzcu4A.png

IE11 (bad, values not plotted and only displays first graph)
http://i.imgur.com/T1xBxKI.png

Edge (bad, values plotted but second graph leaks over first one)
http://i.imgur.com/wY7LIoQ.png

**Comment by sysstat** [comment]
Thank you Steve for these interesting comments. Yet as I'm new with SVG, I don't have any fix for these problems.
Wrt Edge, it seems that the `vector-effect="non-scaling-stroke"` is not supported.
I don't know what's going wrong with IE11.
If anybody has a clue...

**Comment by stevekay** [comment]
The w3 validator isn't liking the `vector-effect` aspect either. 

https://validator.w3.org/check?uri=http%3A%2F%2Fstevekay.github.io%2F&charset=%28detect+automatically%29&doctype=Inline&group=0

**Comment by sysstat** [comment]
@stevekay I have fixed all the warnings and errors provided by the w3 validator.
Could you please check the resulting SVG output with Edge and IE please?
NB: Create an SVG file, not and HTML one:
sadf -g -- -A >graph.svg
Then open the graph.svg file in the browsers.
Thanks.

**Comment by stevekay** [comment]
Looking better.  Plagued by Microsoft's rendering still though.

Chrome 49 (good)
http://i.imgur.com/s0wdiLZ.png

Opera 35 (good)
http://i.imgur.com/H1xKas7.png

Firefox 44 (good)
http://i.imgur.com/oLVVmUw.png

IE11(better than before, but looking a bit erratic - thick lines, and network graphs offset/wrong)
http://i.imgur.com/ofykJbz.png
http://i.imgur.com/vIfLfoo.png

Edge (as IE11, better than before, but thick lines and network graphs offset/wrong)
http://i.imgur.com/DDdeXXp.png
http://i.imgur.com/OrRCLuy.png

**Comment by stevekay** [comment]
Background on the non-scaling-stroke issue.  Bug and MS don't plan to fix.
https://connect.microsoft.com/IE/feedback/details/788819/svg-non-scaling-stroke

**Comment by sysstat** [comment]
So this is now clear. Thank you Steve.

**Comment by stevekay** [comment]
Worth updating the sadf man page to mention the Microsoft rendering, avoid a ton of bug reports / emails later?  I was thinking about possible workarounds but it would mean getting rid of the transform/scale stuff, rather a big challenge.  So solution is just to use any non-microsoft browser, job done....
