### ISSUE TITLE
[RFE] collect /proc/net/softnet_stat

### ISSUE THREAD

**Issue by pschiffe** [sysstat/sysstat#110]
Hello,

we received RFE to collect stats from the /proc/net/softnet_stat file, as it contains stats that may indicate packet drops, which is currently invisible to sar.

Currently, softnet_stat is better described by this tool and mail thread, as its documentation is lacking: https://www.mail-archive.com/netdev@vger.kernel.org/msg100868.html

What do you think about including this stats into sa data files?

Thanks,

peter

**Comment by sysstat** [comment]
Hi,
If there is a real need to have these stats at hand then yes, we can consider adding them to sar.
BTW, sar already displays number of packets dropped per second (rxdrop/s & txdrop/s with sar -n EDEV) but I imagine you are talking about something different here?
Regards,
Sebastien.

**Comment by pschiffe** [comment]
Yes, those are different stats. Stats from the /proc/net/softnet_stat are about the softirqs that handles networking, so the drops on softnet_stat aren't included in rxdrop/s at all.

**Comment by sysstat** [comment]
FYI - Statistics about software-based network processing (those found in /proc/net/softnet-stat file) are now collected and displayed by sar. See corresponding commits on GitHub.
Thanks.
