### ISSUE TITLE
[RFE] add option to display values in human readable format

### ISSUE THREAD

**Issue by pschiffe** [sysstat/sysstat#112]
For example:

```
$ pidstat -r --human 5 1
Linux 4.4.6-200.fc22.x86_64 (work-ntb)  03/31/2016  _x86_64_    (4 CPU)

04:41:06 PM   UID       PID  minflt/s  majflt/s     VSZ     RSS   %MEM  Command
04:41:11 PM  1000      4829    949.50      0.00   2270M   1072M   9.16  thunderbird
```

This option should be available in multiple sysstat programs and final size should be determined automatically, for example `2270M` and `22.7G`

**Comment by sysstat** [comment]
Agreed, as long as it actually is only an option that one can decide to use or not.

**Comment by sysstat** [comment]
Feature added to sysstat commands (sar, iostat, pidstat, tapestat, cifsiostat).

**Comment by pschiffe** [comment]
@sysstat I've just tested this and it's perfect, great job!

**Comment by sysstat** [comment]
Thanks Peter : -)
