### ISSUE TITLE
sysstat 8.1.5 - sar -A 10 360 - Interrupts limited to 256?

### ISSUE THREAD

**Issue by Pitterling** [sysstat/sysstat#113]
Hi, just figured out that the output of above command does not list all interrupts .. in fact on my system interesting interrupts are in the range of 4xx + 
I know this a quite old sysstat, but unfortunately still used by the big vendors. Is this fixed/changed in a more rececnt version?

Thx

**Comment by stevekay** [comment]
Crikey, v8.1.5, that was released over 7 years ago. You'll be delighted to hear it was increased from 256 to 1024 in v10.1.3.  See http://sebastien.godard.pagesperso-orange.fr/changelog.html "2012/12/23: Version 10.1.3: Increase NR_CPUS and NR_IRQS values." - commit https://github.com/sysstat/sysstat/commit/c658fb186dbb6482db6d11c9a350803f17a3f04c

**Comment by Pitterling** [comment]
Well i know, but the Enterprise versions still rely on that. All SLES11.x and RHEL6.x releases still ship this version...
Furthermore i have here a system with 1500 Interrupts ... so it seems the value of 1024 is already to small :) - Thanks for the update anyway

**Comment by portante** [comment]
@Pitterling, I hope the would patch it!  If not, I'd file a bug against them to do so.  @pschiffe?

**Comment by pschiffe** [comment]
Well, RHEL6.x ships with sysstat version 9.0.4 with plenty of patches backported. And since RHEL6.5, sysstat supports 1024 interrupts.

Latest upstream sysstat version still supports max 1024 interrupts. Does anybody know how to determine max interrupts supported by current Linux kernel?

**Comment by stevekay** [comment]
Latest kernels certainly appear to use the 1024 max.

[linux/arch/x86/include/asm/mpspec.h](https://github.com/torvalds/linux/blob/9256d5a308c95a50c6e85d682492ae1f86a70f9b/arch/x86/include/asm/mpspec.h)


````
#define MAX_MP_BUSSES		256
/* Each PCI slot may be a combo card with its own bus.  4 IRQ pins per slot. */
#define MAX_IRQ_SOURCES		(MAX_MP_BUSSES * 4)
````

**Comment by sysstat** [comment]
FYI: Commit 8c151ea increased max number of interrupts to 4096.
Running my tests on Travis CI system failed because their number of interrupts (1857) was greater than the previous max (1024).
