### ISSUE TITLE
nfsiostat command output doesn't align the values with the correct columns

### ISSUE THREAD

**Issue by KunX** [sysstat/sysstat#114]
On the newer versions of sysstat, the nfsiostat binary is reporting the values in the wrong places. They don't align with the respective columns at all. That makes it really hard to build some monitoring scripts that use the command, because of the inconsistency between OS versions.

```
192.168.17.1:/var/www mounted on /var/www:

   op/s		rpc bklog
   0.60
	   0.00
read:          
  ops/s		   kB/s		  kB/op		retrans		avg RTT (ms)	avg exe (ms)
		  0.013
	  2.150
	169.751
       0 (0.0%)
	 11.842
	 11.960
write:         
  ops/s		   kB/s		  kB/op		retrans		avg RTT (ms)	avg exe (ms)
		  0.000
	  0.061
	453.392
       0 (0.0%)
	 97.151
	120.760
```

**Comment by pschiffe** [comment]
nfsiostat is no longer part of the sysstat package, now it's in the nfs-utils package.
https://github.com/sysstat/sysstat/commit/c9e9693d960836e0f059ab6d358af5edcc6fea65

**Comment by KunX** [comment]
Ok, thanks for pointing that out.
