### ISSUE TITLE
sadf man page : options

### ISSUE THREAD

**Issue by stevekay** [sysstat/sysstat#116]
`sadf` man page reads

    -O opts
      Use the specified options to control SVG output displayed by sadf -g.  Possible options are:

To align consistently with other args which can be OR'd (e.g. `sadf -S`, `sar -j`), perhaps should read as below.  Other sysstat components use upper case for args of this type too, or is it intentionally lower case for `sadf` options?

    -O { autoscale | oneday | skipempty | ... }

**Comment by sysstat** [comment]
Yes, using lower case args is a deliberate choice from me here. Wrt the man page, I will update it as follow:

-O { opts [,...] }

**Comment by sysstat** [comment]
Done (commit 7955a20).
