### ISSUE TITLE
wrong comment

### ISSUE THREAD

**Issue by qlq3763** [sysstat/sysstat#122]
In file iostat.c: 
/*
 ***************************************************************************
 * Main loop: Read I/O stats from the relevant sources and display them.
 *
 * IN:
 * @count	Number of lines of stats to print.
 * @rectime	Current date and time.
 ***************************************************************************
 */
void rw_io_stat_loop(long int count, struct tm *rectime)
{

I think " * @count	Number of lines of stats to print." 
should be " * @count	Number of times of stats to print."(count means how many times stats to print), right?

**Comment by sysstat** [comment]
You're right, or "number of reports to print", as stated in the manual page, since a report can include several devices and so, several lines of statistics.
