### ISSUE TITLE
Questions about sadf output cvs format file's first line

### ISSUE THREAD

**Issue by BrytonLee** [sysstat/sysstat#123]
sadf -hd can output cvs format file, but I saw that file's first line didn't contain full fields according to the number of variant kind devices(e.g CPU Network port USB port), it just show fields one time and put "[...]" postfix instead of duplicating previous fields.  for example: 

> # hostname;interval;timestamp;CPU;%usr;%nice;%sys;%iowait;%steal;%irq;%soft;%guest;%gnice;%idle**[...]**;

on my test box, I have 64 H/W threads(with HT turn on),  ak 64 logical CPUs,  if the head line just show fields one time,  it's a bit clumsy to use the data directly. 

so I want to change "[...]" back to duplicate fields according to the number of variant devices.  is that OK?

**Comment by sysstat** [comment]
Yes, that's OK.
I think my initial idea was to get something easier to read for the user. But I also understand that it's not the best solution if you want to export data to a spreadsheet.

**Comment by BrytonLee** [comment]
I have modified sysstat-10.1.5's source code which come from centOS src.rpm.  I made header fields duplicate act[i]->nr times. But I found TTY related fields goes wrong, on my test box, (1)sar.sar saved the number of fields about TTY less than the number of header line's fields about TTY; and (2) the number of entries about TTY less than act[i]->nr. 

is that normal, or how that can be happen under what situation? thanks.

**Comment by sysstat** [comment]
OK, now I remember why "[...]" was displayed in the header line by sadf.
In fact, sar/sadc preallocates structures for devices which may be added after the /var/log/sa/saDD file has been created. So act[i]->nr is the total number of structures allocated for this activity (network statistics, TTY statistics, etc.), which is a number greater than (or equal to) the actual number of devices really used. There is no easy way to guess the correct number of devices for an activity (I mean, it depends on the activity). Moreover, the number of devices may vary within the same datafile, for example if a device has been dynamically added or removed. So the header line content cannot  been statically defined either. Hence the use of "[...]".
You can tell sar/sadc to not preallocate structures when compiling them ("./configure prealloc=0 ; make") but I would not recommend this as statistics for dynamically added devices wouldn't be collected.
