### ISSUE TITLE
sadf in sysstat-11.2.0 produces invalid JSON output: Floats with comma instead of dot

### ISSUE THREAD

**Issue by andy-maier** [sysstat/sysstat#128]
This command on Ubuntu 16.04 on x86:

```
$ sadf -j -- -B 60 1 
```
produces the following output, which contains float numbers represented with a comma instead of a dot (i.e. `4,97` instead of `4.97`). That is invalid JSON according to RFC7159 (and it fails in Python `json.loads()`).

```
{"sysstat": {
	"sysdata-version": 3.1,
	"hosts": [
		{
			"nodename": "maiera-ub16",
			"sysname": "Linux",
			"release": "4.4.0-38-generic",
			"machine": "x86_64",
			"number-of-cpus": 4,
			"file-date": "2016-10-17",
			"file-utc-time": "07:05:09",
			"statistics": [
				{
					"timestamp": {"date": "2016-10-17", "time": "07:15:01", "utc": 1, "interval": 509},
					"paging": {"pgpgin": 4,97, "pgpgout": 7,53, "fault": 61,66, "majflt": 0,02, "pgfree": 103,46, "pgscank": 0,00, "pgscand": 0,00, "pgsteal": 0,00, "vmeff-percent": 0,00}					"fchosts": [

					]
				}
			],
			"restarts": [
			]
		}
	]
}}
```

**Comment by andy-maier** [comment]
I was able to circumvent this in Python with this transformation, before parsing the result string:

```
 result_str = re.sub(r'(: *[0-9]+),([0-9]+[,}])', r'\1.\2', result_str) 
```

It would still be good to fix this issue in sadf.

I was able to verify this with sadf 11.2.0 (on x86 with Ubuntu 16.04) and with sadf 10.1.5 (on s390x with RHEL 7.2). Seems to be there for quite a while now. Don't know why nobody else ran into this.

**Comment by sysstat** [comment]
Thank you for this (real) bug report!
In fact this bug may happen or not depending on the locale you are using.
The fix (to come soon) will set LC_NUMERIC variable to "C" to make JSON output locale independent and the numerical values use a decimal point.
