### ISSUE TITLE
provide available free memory in sar -r

### ISSUE THREAD

**Issue by juliantaylor** [sysstat/sysstat#133]
since version 3.14 Linux provides the `MemAvailable` in `/proc/meminfo` which reports the memory an application can use without swapping. Computing it from other variables is possible but difficult.
See https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0

As this value is often of interest for monitoring it would be nice when it were be exposed by `sar -r`

**Comment by sysstat** [comment]
I agree to add this new value to sar in next sysstat version.

**Comment by juliantaylor** [comment]
that was fast thanks.
But I think it would be better to put it into the default `-r` output and not only into `ALL`. It has more practical use than some of the existing keys in the default output.

**Comment by sysstat** [comment]
Yes, I wasn't sure where to add it. I will move it at the end of the default `-r` output (but I'm wondering whether this can break tools that parse sar's output as it will appear as a new field inserted in the `-r ALL` output...)

**Comment by juliantaylor** [comment]
that is a concern, but you do provide better machine readable output for users to use that is more flexible in this regard (e.g. decent sadf -p parsing scripts should not break when encountering new keyed lines)
I think it is not reasonable to never ever change the intended human readable for the sake of some scripts anticipating new fields.
Didn't this situation already come up in the past?

I think you did not yet update the sar manpage to list kbavail

**Comment by sysstat** [comment]
Yes, sadf is actually intended for this. So I shouldn't have such reservations :-) This situation may probably have already come up in the past, but I didn't have qualms at that time :-)
I will complete the work soon, including updating the man page.
Thanks.
