### ISSUE TITLE
incorrect gcc warning in svg_stats.c

### ISSUE THREAD

**Issue by DigiTester** [sysstat/sysstat#137]
Line 4479, "char *item_name;" warning isn't actually correct, but it might be nice to clean it up since this isn't performance-critical code.  I think initialising it to nullptr should work.

svg_stats.c: In function ‘svg_print_filesystem_stats’:
svg_stats.c:4525:8: warning: ‘item_name’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (!item_name[0]) {

But, to get there you need no matching graph and no free graph entries, and there's an explicit test for that in the code already.

**Comment by sysstat** [comment]
Fixed (I initialized variable to NULL as suggested).
Thanks.
