### ISSUE TITLE
sadf generates incredibly tall, thin SVGs

### ISSUE THREAD

**Issue by aspiers** [sysstat/sysstat#138]
If I do

    sadf -g sa19 -- -A > sa19.svg

then I get around 100 charts stacked vertically on top of each other, so the SVG has an incredibly tall/thin aspect ratio.  This is really quite inconvenient to view.  It would be cool if there was an option to also fit multiple charts on each row.

If this sounds like something you might implement, it might be worth allowing related statistics to be grouped in a vertical stack for easy comparison.  For example, ideally all statistics relating to a particular network interface, or to the CPU load, could be in the same vertical group.

**Comment by sysstat** [comment]
Maybe I could add an option that would make all charts from the same activity and for the same device appear on the same row.
We would get:
[CPU all]
[CPU#0]
...
[CPU#n]
[Task creation] [Switching Activity]
[Swap activity]
[Paging activity#1] [Paging activity#2] [Paging activity#3]
...
[Net stats#1 NIC#1] [Net stats#2 NIC#1] [Net stats#3 NIC#1] [Net stats#4 NIC#1]
[Net stats#1 NIC#2] [Net stats#2 NIC#2] [Net stats#3 NIC#2] [Net stats#4 NIC#2]
etc.

**Comment by aspiers** [comment]
Yes something like that sounds great - thanks a lot!
