### ISSUE TITLE
[Question] Existence of curses-ish interface?

### ISSUE THREAD

**Issue by abcarroll** [sysstat/sysstat#139]
Hello.

Just wanted to ask if anyone is aware of a curses/curses-like interface available for `sar`?

If anyone here has ever used `iptraf` -- I'm talking about something like this, where there is a menu that could be traversed to select which metrics to view.

I'd very much like to create one, if one doesn't exist already.  I really do not want to duplicate effort if something is already pre-existing out there.

And, to Sebastien Godard, if you read this -- thank you for this wonderful piece of software.

**Comment by sysstat** [comment]
Hi,
I'm not aware of any curses interfaces for sar or any sysstat commands.
Cheers.
