### ISSUE TITLE
[RFE] mpstat: provide a way to summarize CPU statistics based on numa node placement

### ISSUE THREAD

**Issue by msekletar** [sysstat/sysstat#140]
On systems with many CPUs it is often very useful to look at workload distribution among NUMA nodes on the system. Currently mpstat can show per CPU statistics, but it can't do summary statistics (average) for all CPUs on a given NUMA node.

For example, on a system with 64 CPUs and 4 NUMA nodes output could look like this,

```
05:53:49 PM NODE    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
05:53:54 PM  all   82.69    0.00    0.52    0.19    0.21    0.12    0.00    0.00    0.00   16.27
05:53:54 PM    0   86.45    0.00    0.29    0.16    0.23    0.12    0.00    0.00    0.00   12.75
05:53:54 PM    1   85.85    0.00    0.93    0.21    0.21    0.11    0.00    0.00    0.00   12.69
05:53:54 PM    2   78.25    0.00    0.58    0.15    0.20    0.09    0.00    0.00    0.00   20.73
05:53:54 PM    3   80.33    0.00    0.26    0.19    0.18    0.09    0.00    0.00    0.00   18.96
```

Here is a script that does post-processing of ```mpstat``` output in order to achieve this per NUMA node summary. I think that such functionality should be generally useful to more people and hence direct support in mpstat is warranted.

https://github.com/jhladka/MPSTAT2NODE/blob/master/mpstat2node.py

**Comment by jirka-h** [comment]
I vote for this feature. I deal with systems which have 100+ CPUs. On such systems, individual CPU load is not so important anymore. We are much more interested to know how is load distributed among the NUMA nodes. Having NUMA nodes support in mpstat would be indeed very useful.

**Comment by sysstat** [comment]
Agreed to add this feature to mpstat.
Which file in /proc or /sys gives the binding between CPU and NUMA nodes?

**Comment by msekletar** [comment]
It is possible to figure out this information from sysfs. For example, this is a content of ```/sys/devices/system/cpu/cpu0/``` directory from my machine,

```
total 0
drwxr-xr-x.  7 root root    0 Feb  8 17:06 cache
lrwxrwxrwx.  1 root root    0 Feb  7 08:46 cpufreq -> ../cpufreq/policy0
drwxr-xr-x. 11 root root    0 Feb 10 16:58 cpuidle
-r--------.  1 root root 4096 Feb  9 14:25 crash_notes
-r--------.  1 root root 4096 Feb  9 14:25 crash_notes_size
lrwxrwxrwx.  1 root root    0 Feb 10 16:58 driver -> ../../../../bus/cpu/drivers/processor
lrwxrwxrwx.  1 root root    0 Feb 10 16:58 firmware_node -> ../../../LNXSYSTM:00/LNXCPU:00
drwxr-xr-x.  2 root root    0 Feb 10 16:58 hotplug
drwxr-xr-x.  2 root root    0 Feb 10 16:58 microcode
lrwxrwxrwx.  1 root root    0 Feb 10 16:58 node0 -> ../../node/node0
drwxr-xr-x.  2 root root    0 Feb 10 16:58 power
lrwxrwxrwx.  1 root root    0 Feb 10 10:03 subsystem -> ../../../../bus/cpu
drwxr-xr-x.  2 root root    0 Feb 10 16:58 thermal_throttle
drwxr-xr-x.  2 root root    0 Feb  8 17:06 topology
-rw-r--r--.  1 root root 4096 Feb  9 14:25 uevent
```

As you can see above, there is a symbolic link ```node0``` that points to NUMA node sysfs entry.

https://github.com/torvalds/linux/blob/master/Documentation/ABI/testing/sysfs-devices-system-cpu#L56

**Comment by sysstat** [comment]
OK, thank you :)

**Comment by RobertCElliott** [comment]
Beware that those files are not present if the kernel was compiled with CONFIG_NUMA=n.  That confused the ndctl, an NVDIMM management tool, recently.

**Comment by portante** [comment]
If we are going to do this for `mpstat`, might we consider also doing this for CPU data displayed via `sar`?

**Comment by sysstat** [comment]
Features added to mpstat often end up being included in sar... But at the present time I don't plan to do so.

**Comment by sysstat** [comment]
@msekletar Could you please test patch 060e888 and tell me if all goes well?
Thanks.

**Comment by msekletar** [comment]
I did some basic testing and things look mostly OK. I have noticed only one possible issue. When I run ```./mpstat -n -N ALL 2 1``` I get following output on my laptop (4 CPUs, 1NUMA node),

```
Linux 4.9.6-200.fc25.x86_64 (morgoth.usersys.redhat.com)        04/27/2017      _x86_64_        (4 CPU)

11:33:58 AM NODE    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
11:34:00 AM  all    2.89    0.00    0.63    0.13    0.38    0.00    0.00    0.00    0.00   95.98
11:34:00 AM    0    2.88    0.00    0.38    0.12    0.25    0.00    0.00    0.00    0.00   95.75

Average:    NODE    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
Average:     all    2.89    0.00    0.63    0.13    0.38    0.00    0.00    0.00    0.00   95.98
Average:       0    2.88    0.00    0.38    0.12    0.25    0.00    0.00    0.00    0.00   95.75
```

I am bit puzzled why statistics differ for all nodes and node 0. After all I have only 1 node (node 0) hence in theory  "all == 0" in my case. But maybe I am missing something.

**Comment by msekletar** [comment]
Nevertheless, I will defer more elaborate testing to @jirka-h

**Comment by sysstat** [comment]
@msekletar I had also noticed that statistics were a bit different for all nodes and node 0, e.g:
```
$ ./mpstat -N ALL 2 1
Linux 4.4.14-200.fc22.x86_64 (test.home) 	05/03/17 	_x86_64_	(8 CPU)

11:35:46    NODE    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
11:35:48     all    0.31    0.00    0.13    0.00    0.00    0.00    0.00    0.00    0.00   99.56
11:35:48       0    0.38    0.06    0.12    0.00    0.00    0.00    0.00    0.00    0.00   99.50

Average:    NODE    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
Average:     all    0.31    0.00    0.13    0.00    0.00    0.00    0.00    0.00    0.00   99.56
Average:       0    0.38    0.06    0.12    0.00    0.00    0.00    0.00    0.00    0.00   99.50
```

I think this is because individual CPU statistics values don't exactly add up to the global CPU statistics values (as read from the /proc/stat file), and also because mpstat doesn't read all those values atomically. When the interval is short (e.g. 2 seconds in your example), the difference between all nodes and node 0 seems to be important. The difference is less important if you use a longer time interval (i.e. if each counter gets the possibility to change more drastically and as a consequence flattens the few ticks difference between global CPU counter value and the sum of each individual CPU counter values):

```
$ ./mpstat -N ALL 10 1
Linux 4.4.14-200.fc22.x86_64 (kluane.home) 	05/03/17 	_x86_64_	(8 CPU)


11:53:18    NODE    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
11:53:28     all    1.51    0.01    0.52    0.01    0.00    0.00    0.00    0.00    0.00   97.94
11:53:28       0    1.51    0.00    0.51    0.01    0.00    0.00    0.00    0.00    0.00   97.95

Average:    NODE    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
Average:     all    1.51    0.01    0.52    0.01    0.00    0.00    0.00    0.00    0.00   97.94
Average:       0    1.51    0.00    0.51    0.01    0.00    0.00    0.00    0.00    0.00   97.95

```

**Comment by sysstat** [comment]
@jirka-h If you have the possibility to test this version of mpstat, please do and tell me if anything goes wrong!

**Comment by sysstat** [comment]
@msekletar FYI commit e291af0 changes how mpstat gets the statistics for node "all": They are now calculated as the sum of each individual CPU statistics. mpstat no longer uses the global CPU statistics values provided by the /proc/stat file on its first line.
As a consequence your statistics will no longer differ between all nodes and node 0 in your example above.
