### ISSUE TITLE
[enhancement ] Allow sadf to read from stdin

### ISSUE THREAD

**Issue by theblazehen** [sysstat/sysstat#144]
Attempting to load from /dev/stdin doesn't work as it attempts to seek in the file

**Comment by sysstat** [comment]
Why would you like sadf to read from stdin? Do you have a use case where this feature would be useful?

**Comment by theblazehen** [comment]
Yes, doing a single run of sadc piped to sadf which outputs the data in json format, without needing to use a temp file somewhere

**Comment by sysstat** [comment]
I had a look at the code. Unfortunately this feature cannot be easily added to sadf: sadf may read its input file several times, rewinding it when necessary, to display each consecutive activity. This cannot be easily done when reading from stdin, or at least without adding a lot of new code which is not wanted here.
