### ISSUE TITLE
Tests failures on big endian archs ("Endian format mismatch")

### ISSUE THREAD

**Issue by roblub** [sysstat/sysstat#145]
Hi

On big endian archs the tests included in sysstat 11.5.5 fail with the following error:

```
dh_auto_test -v -Sautoconf --parallel
	make -j4 test VERBOSE=1
make[2]: Entering directory '/«PKGBUILDDIR»'
make[3]: Entering directory '/«PKGBUILDDIR»'
001
make[3]: Leaving directory '/«PKGBUILDDIR»'
make[3]: Entering directory '/«PKGBUILDDIR»'
002
make[3]: Leaving directory '/«PKGBUILDDIR»'
make[3]: Entering directory '/«PKGBUILDDIR»'
003
make[3]: Leaving directory '/«PKGBUILDDIR»'
make[3]: Entering directory '/«PKGBUILDDIR»'
004
make[3]: Leaving directory '/«PKGBUILDDIR»'
make[3]: Entering directory '/«PKGBUILDDIR»'
005
make[3]: Leaving directory '/«PKGBUILDDIR»'
make[3]: Entering directory '/«PKGBUILDDIR»'
006
make[3]: Leaving directory '/«PKGBUILDDIR»'
make[3]: Entering directory '/«PKGBUILDDIR»'
007
make[3]: Leaving directory '/«PKGBUILDDIR»'
make[3]: Entering directory '/«PKGBUILDDIR»'
008
make[3]: Leaving directory '/«PKGBUILDDIR»'
make[3]: Entering directory '/«PKGBUILDDIR»'
009
Invalid system activity file: tests/data-10.3.1
File created by sar/sadc from sysstat version 10.3.1
Endian format mismatch
Makefile:578: recipe for target 'unit' failed
```
Full build logs can be found at https://buildd.debian.org/status/fetch.php?pkg=sysstat&arch=mips&ver=11.5.5-1&stamp=1492984566&raw=0 or https://buildd.debian.org/status/fetch.php?pkg=sysstat&arch=hppa&ver=11.5.5-1&stamp=1492985470&raw=0 (Logs for other args can be found at https://buildd.debian.org/status/package.php?p=sysstat&suite=experimental but the link might not be permanent).

**Comment by sysstat** [comment]
Thanks Robert for this bug report.
Not sure about this, but are you cross compiling sysstat (e.g compiling sysstat for big-endian arch on a little-endian machine?)

**Comment by roblub** [comment]
No, all compilations were done on Debian build machines, which are real boxes, as far as I know, so no cross compilation should be involved. 

I've just logged into a powerpc box, compiled unmodified version (i.e. without any Debian patches) of sysstat, and was able to reproduce the `make test` failure. 

I am also attaching compressed  result of `./sadc 1 5` command on that box.  Maybe this little file will help to diagnose/fix the issue with unit tests.   I can reproduce the issue on an amd64 box with it, i.e. `sar -f sadc-powerpc-output` fails with `Endian format mismatch`.   The same command on a mips box works correctly.

[sadc-powerpc-output.gz](https://github.com/sysstat/sysstat/files/962857/sadc-powerpc-output.gz)
