### ISSUE TITLE
sadc crashes because of unaligned memory accesses + Proposed Fix

### ISSUE THREAD

**Issue by manojgupta83** [sysstat/sysstat#148]
We are seeing crashes in sysstat because of unaligned memory accesses on ARM. 

Summary:

Several structs in sysstat need 16 byte alignment. However, there are many pointer casts that do not guarantee 16 byte alignment. 

struct stats_io {
        unsigned long long dk_drive             __attribute__ ((aligned (16))); // This is expected to be 16 bytes aligned
        unsigned long long dk_drive_rio         __attribute__ ((packed));
        unsigned long long dk_drive_wio         __attribute__ ((packed));
        unsigned long long dk_drive_rblk        __attribute__ ((packed));
        unsigned long long dk_drive_wblk        __attribute__ ((packed));
};

sa_wrap.c

__read_funct_t wrap_read_io(struct activity *a)
{
        struct stats_io *st_io
                = (struct stats_io *) a->_buf0;  // Unsafe pointer cast. st_io might not be 16 byte aligned

        /* Read stats from /proc/diskstats */
        read_diskstats_io(st_io);  // This will crash because of unaligned accesses

        return;
}

Proposed Fix:
Use posix_memalign wtih 16 bytes alignment request instead of realloc. This fixed the crashes in our testing.

A patch to fix the issue is atta
[sysstat-align.patch.txt](https://github.com/sysstat/sysstat/files/979897/sysstat-align.patch.txt)
ched.

**Comment by manojgupta83** [comment]
Discussion about crash and SIMD loads on ARM.
http://lists.infradead.org/pipermail/linux-arm-kernel/2017-May/504731.html

**Comment by sysstat** [comment]
Thanks for this bug report and proposed fix.
Your patch has been applied to current sysstat version.

**Comment by sysstat** [comment]
This bug is fixed with the new binary format provided by sysstat 11.7.1.
Structures now need at most 8 byte alignment.
See commit df0c8a0.
