### ISSUE TITLE
sadf creates huge svg file from small sar file

### ISSUE THREAD

**Issue by lgunnar** [sysstat/sysstat#150]
I get a huge svg file when running sadf.
I did this:

/usr/local/bin/sar -A -o /tmp/zapp.sar  5 2
/usr/local/bin/sadf -g /tmp/zapp.sar -- -A 5 > /tmp/zapp.svg
and the resulting files:

         84436 May 22 09:59 /tmp/zapp.sar
     874074112 May 22 10:00 /tmp/zapp.svg

That can't be right, can it? Any ideas what is going on?

I aborted the sadf command before it could finish.

The last lines in the svg are

`<text x="0" y="0" style="fill: white; stroke: none; font-size: 12px; text-anchor: end">88924125.</text>
<polyline points="0,88924150.00 720,88924150.00" style="vector-effect: non-scaling-stroke; stroke: #202020" transform="scale(1,-0.000000)"/>
<text x="0" y="0" style="fill: white; stroke: none; font-size: 12px; text-anchor: end">88924150.</text>
<polyline points="0,88924175.00 720,88924175.00" style="vector-effect: non-scaling-stroke; stroke: #202020" transform="scale(1,-0.000000)"/>
<text x="0" y="0" style="fill: white; stroke: none; font-size: 12px; text-anchor: end">88924175.</text>
<polyline points="0,88924200.00 720,88924200.00" style="vector-effect: non-scaling-stroke; stroke: #202020" transform="scale(1,-0.000000)"/>
<text x="0" y="0" style="fill: white; stroke: none; font-size: 12px; text-anchor: end">88924200.</text>
<polyline points="0,88924225.00 720,88924225.00" style="vector-effect: non-scaling-stroke; stroke: #202020" transform="scale(1,-0.000000)"/>
<text x="0" y="0" style="fill: white; stroke: none; font-size: 12px; text-anchor: end">88924225.</text>
<polyline points="0,88924250.00 720,88924250.00" style="vector-effect: non-scaling-stroke; stroke: #202020" transform="sca
`

I checked out the latest version from github a few days ago (version.h says 11.5.7) and compiled it my self, and I'm using CentOS 5.7. 
It works fine in redhat 5.9

**Comment by sysstat** [comment]
I am unable to reproduce the problem. Could you please send me (sysstat at orange dot fr) your zapp.sar file?
Thanks.

**Comment by lgunnar** [comment]
It worked fine with the latest version you sent me. So I will close this, and others that have the same issue should try the next release (11.5.7)
