### ISSUE TITLE
default colours are suboptimal for light backgrounds

### ISSUE THREAD

**Issue by pschiffe** [sysstat/sysstat#151]
Hello,

currently selected default colours are suboptimal for terminals with light backgrounds, especially the bold yellow text:
![iostat-white-bg](https://cloud.githubusercontent.com/assets/3899107/26309243/8fd13dce-3efc-11e7-855d-40e5d87a6d98.png)

Ideally, the default colours should be usable with both, dark and light terminal backgrounds. I was playing a bit with the colours, and maybe this could be a good default?
```export S_COLORS_SGR='C=33;22:H=31;1:I=32;22:M=35;1:N=34;1:R=31;22:Z=34;22'```

It's blue -> magenta -> red according to the value and yellow comments:
![sar-new-colours](https://cloud.githubusercontent.com/assets/3899107/26310001/8341483a-3eff-11e7-8227-daee9a5c28c4.png)

**Comment by sysstat** [comment]
Peter,
I must admit than I personally use a dark terminal.
Anyway you're right (again... :-)) I will switch the default colors to those you suggested.
Thanks.

**Comment by VTAS-JC** [comment]
i have a better suggestion - no damn colors at all (by default)

i can't be the only one who wants simple "black and white"; if someone wants to colorize an output give them an option to enable this feature, or at the very least an option to completely disable

**Comment by sysstat** [comment]
You're not the only one who wants that, but you're close... That's why stats are displayed in color by default.
To disable this feature, just read the manual:
```
export S_COLORS=never
```
