### ISSUE TITLE
Pidstat - no output (i.mx6)

### ISSUE THREAD

**Issue by Alex66955** [sysstat/sysstat#154]
Hi,

I cross compiled systat for my i.mx6 dual light target. 
Every tool works fine except pidstat. 

There is no output if I call it:
`
root@phyboard-mira-imx6-7:/data/sysstat-master# ./pidstat
Linux 4.1.36-i.MX6-PD-morty (phyboard-mira-imx6-7)      05/18/17        _armv7l_        (2 CPU)
`

Proc is mounted (example):
`
/data/sysstat-master# cat /proc/365/stat
365 (QtWebProcess) R 174 173 173 0 -1 4194304 115172 0 175 0 207487 3377 0 0 30 10 9 0 119815 463757312 32107 4294967295 65536 68944 2122907200 2122904528 1968630112 0 0 4096 671878 0 0 0 17 1 0 0 0 0 0 134480 134844 15835136 2122907426 2122907463 2122907463 2122907610 0
`

Are there suggestions or solutions?

**Comment by sysstat** [comment]
Which version of sysstat are you using?
Also try to enter `pidstat -p ALL`, this should quite probably display something...

**Comment by Alex66955** [comment]
The pidstat version is 11.5.7

The output of -p "All" is:

```
./pidstat -p ALL
Linux 4.1.15-rel_imx_4.1.15_1.2.0_ga-20160902 (MBa6x)   03/31/16        _armv7l_        (2 CPU)
22:02:09      UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
```

**Comment by sysstat** [comment]
Please send me (sysstat at orange dot fr) the output of the following command: `strace ./pidstat -p ALL`. Thanks.
