### ISSUE TITLE
Pidstat -h modifies the Time field without declaring it will do so.

### ISSUE THREAD

**Issue by egriffith** [sysstat/sysstat#155]
Currently I'm running sysstat version 10.1.5 on CentOS 7. If I run "pidstat" I get:

```
02:13:08 PM   UID       PID    %usr %system  %guest    %CPU   CPU  Command
02:13:08 PM     0         1    0.00    0.00    0.00    0.00     1  systemd
```

If I instead run pidstat -h, I get: 

```
#      Time   UID       PID    %usr %system  %guest    %CPU   CPU  Command
 1498587221     0         1    0.00    0.00    0.00    0.00     1  systemd

```

Where Time seems to be seconds-since-epoch, rather than system time. This becomes an issue since for scripts it can be convenient to have "pidstat -ur" tracking both memory and CPU. Without "-h" they get reported in two separate tables, with -h they are reported in a single table (desired), but TIME is reported in seconds-since-epoch (undesired). 

Furthermore the man page makes no mention of this change in behavior for the "-h" flag. 

>       -h     Display all activities horizontally on a single line. This is intended to make it easier to be parsed by other programs.

If you do not want to modify the actual implementation of the -h flag due to the risk of breaking scripts, I understand, but can we please get this mentioned in the man page and an additional flag added which declares that -h should NOT change the time field?

**Comment by sysstat** [comment]
I will probably add a new flag (-H) to keep the original time format (I plan it for next sysstat version).

**Comment by sysstat** [comment]
Commit 39f3a71 adds option -H that tells pidstat to display time in seconds since the Epoch.
Without this option, time is displayed in the usual system time format. This also means that the default output for option -h (used to display all activities on a single line) has changed: it keeps the system time format instead of time expressed in seconds since the Epoch.
