### ISSUE TITLE
sysstat does not read temperature on a Raspberry Pi

### ISSUE THREAD

**Issue by jonsnow1357** [sysstat/sysstat#156]
When -S POWER is enabled, there is no temperature data that is logged on a Raspberry Pi.

[~]$ uname -a
Linux rpi03 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux
[pi@rpi03 00:35:28]
[~]$ sar -m TEMP
Requested activities not available in file /var/log/sysstat/sa03
[pi@rpi03 00:35:33]
[~]$ sar -m FREQ
Linux 4.9.35+ (rpi03) 	03/08/17 	_armv6l_	(1 CPU)

00:10:24     LINUX RESTART	(1 CPU)

12:15:02 AM     CPU    wghMHz
12:25:01 AM     all    700.00
12:35:01 AM     all    700.00
Average:        all    700.00

I can provide information on how to get the temperature on Raspberry Pi (see below), however it's in python since C is not really my strong point :(

      fPath = "/sys/class/thermal/thermal_zone0/temp"
      with open(fPath, "r") as fIn:
        tmp = float(fIn.readlines()[0])
        self.data["temp"] = round((tmp / 1000.0), 1)

**Comment by sysstat** [comment]
sysstat uses the lm_sensors library to read CPU temperature and other sensors data.
Make sure that you have this library installed on your system, and that sysstat has been actually linked against it (this should be the case by default).
Also check that your hardware is supported by lm_sensors (see https://github.com/groeck/lm-sensors).

**Comment by jonsnow1357** [comment]
thanks, 
I have lm_sensors installed but it does not detect any sensors ... I'll try to raise this to lm_sensors then
