### ISSUE TITLE
sadc crashes on a mtab file with really long lines

### ISSUE THREAD

**Issue by roblub** [sysstat/sysstat#162]
Sebastien

I received https://bugs.debian.org/872926, whose reporter observed the following crash:

```
> root@turkey:~# /usr/lib/sysstat/sadc -F -L -S DISK 1 1 /var/log/sysstat
Segmentation fault
```

It turned out that this is related to use of the overlay2 filesystem with docker, which causes lines in /etc/mtab to be longer that 512 bytes (see the [mtab.out file attached to the Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=872926;filename=mtab.out;msg=15).)
The crash occurs in the get_filesystem_nr() function which calls strchr(line, ' ') but fails to check if its result is not NULL. 

I've just created a patch [fix-mtab-reading-patch.txt](https://github.com/sysstat/sysstat/files/1247157/fix-mtab-reading-patch.txt) that adds this check, and when a single mtab entry requires more that one call to fgets() (i.e. the entry is longer than 512 bytes), it ignores outcome of the second and following calls. 

Regards,
robert

**Comment by sysstat** [comment]
Hi Robert,

Thank you for your bug report and your patch.
Your patch fixes the segmentation fault we get with "sadc -S DISK...".
I have noticed that the same bug exists with "sadc -S XDISK...", i.e. when filesystem statistics are read by sadc. So I have extended the scope of your patch and have also applied the changes to read_filesystem() function in rd_stats.c.

Regards,
Sebastien

**Comment by hanbaga** [comment]
@sysstat  how can I change sysstat.ioconf to avoid the segment fault, not merge the patch version 11.2.0 ubuntu 16.04

**Comment by sysstat** [comment]
Fixing the problem requires applying the patch, not changing sysstat.ioconf.
