### ISSUE TITLE
How can we eliminate the build differences caused by the time stamps for reproducible build

### ISSUE THREAD

**Issue by waylandzhong** [sysstat/sysstat#164]
When I build sysstat (the latest version 11.6.0), I find the build results are different every time. It seems to be caused by some times tamps, and they may be generated by the code below:

cifsiostat.c:44:#define SCCSID "@(#)sysstat-" VERSION ": " __FILE__ " compiled " __DATE__ " " __TIME__
iostat.c:51:#define SCCSID "@(#)sysstat-" VERSION ": " __FILE__ " compiled " __DATE__ " " __TIME__
mpstat.c:45:#define SCCSID "@(#)sysstat-" VERSION ": "  __FILE__ " compiled " __DATE__ " " __TIME__
pidstat.c:50:#define SCCSID "@(#)sysstat-" VERSION ": " __FILE__ " compiled " __DATE__ " " __TIME__
sadc.c:55:#define SCCSID "@(#)sysstat-" VERSION ": " __FILE__ " compiled " __DATE__ " " __TIME__
sadf.c:44:#define SCCSID "@(#)sysstat-" VERSION ": " __FILE__ " compiled " __DATE__ " " __TIME__
sar.c:45:#define SCCSID "@(#)sysstat-" VERSION ": " __FILE__ " compiled " __DATE__ " " __TIME__
tapestat.c:55:#define SCCSID "@(#)sysstat-" VERSION ": " __FILE__ " compiled " __DATE__ " " __TIME__

As we know, reproducible build is a good way to counter malicious attacks that generate malicious executables, by making it easy to recreate the executable to determine if the result is correct.  How can I eliminate the differences caused by the time stamps? Just remove some code? Or is there any configuration?

If we can't eliminate the difference now, can sysstat support it in later versions?

Thank you.

**Comment by sysstat** [comment]
Not sure if someone still uses these SCCSID strings nowadays. I personally don't. So I think I will remove these lines from sysstat code, and it will fix your problem.

**Comment by waylandzhong** [comment]
Thank you. That would help me a lot. 
May I ask what's the version plan for this？So I can upgrade right the first time.

**Comment by sysstat** [comment]
The patch (to come soon) will be included in current development version (11.7.1) and also back ported to stable branches (11.6.1, 11.4.7 and 11.2.13).
I can't tell you exactly when all those versions are available (maybe in next October or November).

**Comment by waylandzhong** [comment]
Thanks :)
