### ISSUE TITLE
'00' byte after values when --human is not set

### ISSUE THREAD

**Issue by cpaelzer** [sysstat/sysstat#165]
Hi,
if --human is not set (the default) then after percentages there is no '%' but instead there should be nothing.
But since commit 33557c3d this is broken.

It does not initialize the unit as:
char u = '\0';

But printing that only in consoles appears as "nothing".
In the raw output that prints a literal '00' byte.

To reproduce just run e.g. pidstat and redirect to a file:
1. in vim you'll see invalid chars as a '@' sign
2. in hexdump and similar you'll see a '00'

Instead of the char we would need a zero length string.
Alternatively the check at the top could set a boolean and at the loop it could do
if (percent) printf('%')
I'll prepare a PR for both so you can pick what you prefer.

**Comment by cpaelzer** [comment]
Suggested changes would either change
[strings](http://paste.ubuntu.com/25520593/) or add a [flag](http://paste.ubuntu.com/25520595/)

I'll test the latter which I like more and only propose that.
Having the other here as alternative is enough, I thought it would be closer to the style it is coded at the moment but it reads "bulky".

**Comment by cpaelzer** [comment]
Ok, changes build and achieve the desired effect - now pushing the PR.

**Comment by cpaelzer** [comment]
Should get auto-linked but to be sure - see PR: https://github.com/sysstat/sysstat/pull/166

**Comment by sysstat** [comment]
Thanks for this bug report and corresponding fix. Good work.
