### ISSUE TITLE
more output columns as expected in the TTY header when converting a binary file to csv

### ISSUE THREAD

**Issue by salimchehab** [sysstat/sysstat#168]
This is the sar text file:
```
08:00:21          TTY   rcvin/s   xmtin/s framerr/s prtyerr/s     brk/s   ovrun/s
08:00:31            0      0.00      0.00      0.00      0.00      0.00      0.00
08:00:31            1      0.00      0.00      0.00      0.00      0.00      0.00
08:00:41            0      0.00      0.00      0.00      0.00      0.00      0.00
08:00:41            1      0.00      0.00      0.00      0.00      0.00      0.00
08:00:51            0      0.00      0.00      0.00      0.00      0.00      0.00
08:00:51            1      0.00      0.00      0.00      0.00      0.00      0.00
```
This is the sar csv file:
```
# hostname;interval;timestamp;TTY;rcvin/s;txmtin/s;framerr/s;prtyerr/s;brk/s;ovrun/s
ubuntu;10;2017-09-29 12:00:31 UTC;0;0.00;0;0.00;0;0.00;0;0.00;0;0.00;0;0.00
ubuntu;10;2017-09-29 12:00:31 UTC;1;0.00;1;0.00;1;0.00;1;0.00;1;0.00;1;0.00
ubuntu;10;2017-09-29 12:00:41 UTC;0;0.00;0;0.00;0;0.00;0;0.00;0;0.00;0;0.00
ubuntu;10;2017-09-29 12:00:41 UTC;1;0.00;1;0.00;1;0.00;1;0.00;1;0.00;1;0.00
ubuntu;10;2017-09-29 12:00:51 UTC;0;0.00;0;0.00;0;0.00;0;0.00;0;0.00;0;0.00
ubuntu;10;2017-09-29 12:00:51 UTC;1;0.00;1;0.00;1;0.00;1;0.00;1;0.00;1;0.00
```

We are getting more values in the sar csv file and the number headers do not match with the number of generate output values:

`1;0.00;1;0.00;1;0.00;1;0.00;1;0.00;1;0.00`

It seems like the `TTY` value is repeating itself.

**Comment by sysstat** [comment]
Can you tell me which version of sysstat you are using?
Thanks.

**Comment by salimchehab** [comment]
sure:
`sysstat version 11.2.0`

**Comment by sysstat** [comment]
Good. Please also send me your sar **binary** datafile, and the contents of the /proc/tty/driver/serial file of your machine (send them to sysstat at orange dot fr). This will help me a lot by making the debugging process much easier.
Thanks again.

**Comment by sysstat** [comment]
@salimchehab Thank you for your help fixing this bug. The fix will be part of next sysstat version and will also be applied to current stable series (11.2.14, 11.4.8, 11.6.2). These versions will be released in January (well... I hope so :-) )
