### ISSUE TITLE
[RFE] Ability to choose which columns and devices to graph with sadc's SVG output

### ISSUE THREAD

**Issue by neilser** [sysstat/sysstat#171]
I just discovered the SVG capability of `sadc` - nice!
Now what I'd really love is a way to directly create graphs for only (for example) a particular disk and a particular data column - e.g. HDD utilisation for /dev/sdb.
Device- and/or column-specific output is a more general wish that I've also noted with `sar`, but at least in the case of the text output it's not too hard with a bit of sed/awk/grep etc. to make the output be whatever you want. That's not so trivial with the SVG output (even though it's XML).
I don't know if this is on the easy or hard end of the spectrum but I'm happy to help if I can.

**Comment by sysstat** [comment]
I can understand your need, at least for SVG graphs.
Generating graphs for all the devices and their partitions may actually appear a bit onerous.
One solution could be to pass a list of devices to sadf (using its option -O, e.g. "`sadf -g -O dev=sda,sdb <...>`") and create a graph only for those devices.
I will think about that...

**Comment by neilser** [comment]
Thanks!
To meet my immediate needs - visualising the disk utilisation daily charts over a couple of weeks - I ended up processing the data in Python: sucking the data into pandas and using matplotlib to graph the results.
That worked pretty nicely but of course it's massively more overhead so I reckon a command-line option for sadf would address a lot of basic use cases.

**Comment by sysstat** [comment]
FYI : Sysstat version 11.7.4 adds new options to sar and sadf, enabling the user to select which network interfaces (`--iface=`), block devices (`--dev=`) and filesystems (`--fs=`) to display, e.g. :
```
sar -n DEV,EDEV -F --iface=eth0,eth1 --fs=/dev/sda6
sadf -g --dev=sda -- -dp > output.svg
(etc.)
````
