### ISSUE TITLE
name bug in ioc_name() ?

### ISSUE THREAD

**Issue by xinglin** [sysstat/sysstat#18]
Hi, It looks like ioc_name does not work as expected. 

I added a line to the following function and it outputs as following. The device name should be "rbd_" but it outputs "emcpower_". 

void read_diskstats_stat(int curr) {
           if ((ioc_dname = ioc_name(major, minor)) != NULL) {
                        if (strcmp(dev_name, ioc_dname) && strcmp(ioc_dname, K_NODEV)) {
                                /*
                                 \* No match: Use name generated from sysstat.ioconf data
                                 \* (if different from "nodev") works around known issues
                                 \* with EMC PowerPath.
                                 */
 ++                             printf("dev_name=%s, ioc_name=%s\n", dev_name, ioc_dname);
                                strncpy(dev_name, ioc_dname, MAX_NAME_LEN);
                        }
                }
}

root@client:/sys/block# /usr/local/bin/iostat -V
sysstat version 10.3.1
(C) Sebastien Godard (sysstat <at> orange.fr)

root@client:/sys/block# /usr/local/bin/iostat
Linux 3.2.16emulab1 (client.ceph.cloud-storage.emulab.net)  03/17/2014  _x86_64_ (64 CPU)

dev_name=rbd4, ioc_name=emcpowerig
dev_name=rbd5, ioc_name=emcpowerhq
dev_name=rbd6, ioc_name=emcpowerha
dev_name=rbd7, ioc_name=emcpowergk
dev_name=rbd8, ioc_name=emcpowerfu
dev_name=rbd9, ioc_name=emcpowerfe
dev_name=rbd10, ioc_name=emcpowereo
dev_name=rbd11, ioc_name=emcpowerdy
dev_name=rbd12, ioc_name=emcpowerdi
dev_name=rbd13, ioc_name=emcpowercs
dev_name=rbd14, ioc_name=emcpowercc
dev_name=rbd15, ioc_name=emcpowerbm
dev_name=rbd16, ioc_name=emcpoweraw
dev_name=rbd17, ioc_name=emcpowerag
dev_name=rbd18, ioc_name=emcpowerq
dev_name=rbd19, ioc_name=emcpowera
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.01    0.00    0.03    0.01    0.00   99.96

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sdb               0.15         0.45         1.19       3090       8184
sdc               0.03         0.11         0.00        744          0
sdd               0.03         0.11         0.00        744          0
sde               0.03         0.11         0.00        744          0
sdg               0.03         0.11         0.00        744          0
sdf               0.03         0.11         0.00        744          0
sda               1.51        25.09         3.61     171981      24724
rbd0              0.03         0.10         0.00        697          4
rbd1              0.03         0.10         0.00        697          4
rbd2              0.03         0.10         0.00        701          4
rbd3              0.03         0.11         0.00        741         24
emcpowerig        0.03         0.11         0.00        741         24
emcpowerhq        0.03         0.10         0.00        701          4
emcpowerha        0.03         0.10         0.00        701          4
emcpowergk        0.03         0.10         0.00        701          4
emcpowerfu        0.03         0.10         0.00        701          4
emcpowerfe        0.03         0.10         0.00        701          4
emcpowereo        0.03         0.10         0.00        701          4
emcpowerdy        0.03         0.10         0.00        701          4
emcpowerdi        0.03         0.10         0.00        701          4
emcpowercs        0.03         0.10         0.00        701          4
emcpowercc        0.03         0.10         0.00        701          4
emcpowerbm        0.03         0.10         0.00        701          4
emcpoweraw        0.03         0.10         0.00        701          4
emcpowerag        0.03         0.10         0.00        701          4
emcpowerq         0.03         0.10         0.00        701          4
emcpowera         0.02         0.10         0.00        678          0
rbd20             0.01         0.05         0.00        344          0
rbd21             0.01         0.05         0.00        344          0
rbd22             0.01         0.05         0.00        344          0
# 

[major, minor] for rbd block devices

root@client:/mnt/sdb2/sysstat-10.3.1# ls -l /dev/rbd*
brw-rw---- 1 root disk 251, 0 Mar 17 16:30 /dev/rbd0
brw-rw---- 1 root disk 250, 0 Mar 17 16:30 /dev/rbd1
brw-rw---- 1 root disk 241, 0 Mar 17 16:44 /dev/rbd10
brw-rw---- 1 root disk 240, 0 Mar 17 16:44 /dev/rbd11
brw-rw---- 1 root disk 239, 0 Mar 17 16:44 /dev/rbd12
brw-rw---- 1 root disk 238, 0 Mar 17 16:44 /dev/rbd13
brw-rw---- 1 root disk 237, 0 Mar 17 16:44 /dev/rbd14
brw-rw---- 1 root disk 236, 0 Mar 17 16:44 /dev/rbd15
brw-rw---- 1 root disk 235, 0 Mar 17 16:45 /dev/rbd16
brw-rw---- 1 root disk 234, 0 Mar 17 16:45 /dev/rbd17
brw-rw---- 1 root disk 233, 0 Mar 17 16:45 /dev/rbd18
brw-rw---- 1 root disk 232, 0 Mar 17 16:45 /dev/rbd19
brw-rw---- 1 root disk 249, 0 Mar 17 16:30 /dev/rbd2
brw-rw---- 1 root disk 231, 0 Mar 17 16:45 /dev/rbd20
brw-rw---- 1 root disk 230, 0 Mar 17 16:45 /dev/rbd21
brw-rw---- 1 root disk 229, 0 Mar 17 16:46 /dev/rbd22
brw-rw---- 1 root disk 248, 0 Mar 17 16:31 /dev/rbd3
brw-rw---- 1 root disk 247, 0 Mar 17 16:43 /dev/rbd4
brw-rw---- 1 root disk 246, 0 Mar 17 16:43 /dev/rbd5
brw-rw---- 1 root disk 245, 0 Mar 17 16:44 /dev/rbd6
brw-rw---- 1 root disk 244, 0 Mar 17 16:44 /dev/rbd7
brw-rw---- 1 root disk 243, 0 Mar 17 16:44 /dev/rbd8
brw-rw---- 1 root disk 242, 0 Mar 17 16:44 /dev/rbd9

**Comment by runsisi** [comment]
solved my problem, many thx:)
