### ISSUE TITLE
Sysstat version 12.0.1 - SLES v12 SP3 - Utilisation per thread exceeds 100% after reboot

### ISSUE THREAD

**Issue by Samodepalace** [sysstat/sysstat#188]
[Bug Details in sysstat v1201 - v2.txt](https://github.com/sysstat/sysstat/files/2310110/Bug.Details.in.sysstat.v1201.-.v2.txt)
If a SLES v12 SP3 server running sysstat version 12.0.1 is rebooted, the next cron scheduled sar data capture will/can include values that exceed 100% per core. The average values also contain greater than 100% values, when using "sar -P ALL". After a period of time (as more samples are written to the /var/log/sayyyyMMdd file the issue effectively resolves itself, with the average values returning to maximum values of 100%.

Comment: This is an observation, Sysstat 11.7.4 and later resolved far more intrusive issues associated with server reboots and reported sar statistics. 

Please see attached files

# sar -P ALL 

[other samples have been removed from this output]
Average:        CPU     %user     %nice   %system   %iowait    %steal     %idle
Average:        all      0.00      0.00      0.00      0.23      0.00    104.53
Average:          0      0.00      0.00      0.00      0.27      0.00    112.23
Average:          1      0.00      0.00      0.00      0.30      0.00    107.68
Average:          2      0.00      0.00      0.00      0.27      0.00    104.92
Average:          3      0.00      0.00      0.00      0.15      0.00    104.06
Average:          4      0.00      0.00      0.00      0.19      0.00    104.03
Average:          5      0.00      0.00      0.00      0.33      0.00    105.91
Average:          6      0.00      0.00      0.00      0.28      0.00    130.17
Average:          7      0.00      0.00      0.00      0.21      0.00    107.54
Average:          8      0.00      0.00      0.00      0.35      0.00    105.12
Average:          9      0.00      0.00      0.00      0.27      0.00    104.28
Average:         10      0.00      0.00      0.00      0.23      0.00    102.72
Average:         11      0.00      0.00      0.00      0.16      0.00    102.50
Average:         12      0.00      0.00      0.00      0.23      0.00    102.44
Average:         13      0.00      0.00      0.00      0.18      0.00    102.59
Average:         14      0.00      0.00      0.00      0.22      0.00    102.72
Average:         15      0.00      0.00      0.00      0.33      0.00    102.33
Average:         16      0.00      0.00      0.00      0.15      0.00    102.64
Average:         17      0.00      0.00      0.00      0.28      0.00    102.68
Average:         18      0.00      0.00      0.00      0.29      0.00    102.45
Average:         19      0.00      0.00      0.00      0.29      0.00    102.55
Average:         20      0.00      0.00      0.00      0.17      0.00    103.46
Average:         21      0.00      0.00      0.00      0.22      0.00    105.79
Average:         22      0.00      0.00      0.00      0.14      0.00    106.20
Average:         23      0.00      0.00      0.00      0.25      0.00    106.88
Average:         24      0.00      0.00      0.00      0.21      0.00    105.55
Average:         25      0.00      0.00      0.00      0.22      0.00    105.11
Average:         26      0.00      0.00      0.00      0.18      0.00    104.46
Average:         27      0.00      0.00      0.00      0.16      0.00    107.10
Average:         28      0.00      0.00      0.00      0.21      0.00    103.30
Average:         29      0.00      0.00      0.00      0.26      0.00    102.73
Average:         30      0.00      0.00      0.00      0.21      0.00    102.74
Average:         31      0.00      0.00      0.00      0.20      0.00    102.64
Average:         32      0.00      0.00      0.00      0.24      0.00    102.54
Average:         33      0.00      0.00      0.00      0.13      0.00    102.96
Average:         34      0.00      0.00      0.00      0.25      0.00    102.46
Average:         35      0.00      0.00      0.00      0.35      0.00    102.51
Average:         36      0.00      0.00      0.00      0.20      0.00    102.45
Average:         37      0.00      0.00      0.00      0.15      0.00    102.60
Average:         38      0.00      0.00      0.00      0.18      0.00    102.44
Average:         39      0.00      0.00      0.00      0.21      0.00    102.57
DL380G9H44U21:/var/log/sa #
[Bug Details in sysstat v1201.txt](https://github.com/sysstat/sysstat/files/2306829/Bug.Details.in.sysstat.v1201.txt)
[sa20180820.gz](https://github.com/sysstat/sysstat/files/2306844/sa20180820.gz)

Kind regards

Pete

**Comment by sysstat** [comment]
Pete,
Looking at the details in sysstat v1201.txt, it seems that you don't call sadc at boot time to insert a LINUX RESTART message in your binary datafile. This is compulsory to indicate that the kernel counters have restarted from 0. In your case this is probably the reason why you get values higher than 100%.
sadc should **always** be called at boot time with no interval / count parameters specified to indicate a system restart.

I didn't have time to look at your sa20180820.gz file but I will do so ASAP to confirm my diagnosis.

**Comment by Samodepalace** [comment]
Please accept my humble apologies, this requirement is clearly documented at:
http://sebastien.godard.pagesperso-orange.fr/documentation.html

I'll investigate and retest

Thanks, Pete

**Comment by Samodepalace** [comment]
A review of the SLES v15 test environment (which comes bundled with sysstat version 11.6.3) indicates that the system is meant to use systemd to insert the LINUX RESTART message into the binary file.

DL380G9H44U37:/mnt/OS_and_Apps/SUSE/SLES15/x86_64 # rpm -qi sysstat
Name        : sysstat
Version     : 11.6.3
Release     : 1.17
Architecture: x86_64
Install Date: Fri Sep  7 07:18:13 2018
Group       : System/Monitoring
Size        : 1379519
License     : GPL-2.0-or-later
Signature   : RSA/SHA256, Fri May 25 17:53:11 2018, Key ID 70af9e8139db7c82
Source RPM  : sysstat-11.6.3-1.17.src.rpm
Build Date  : Fri May 25 17:53:00 2018
Build Host  : sheep22
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : SUSE LLC <https://www.suse.com/>
URL         : http://pagesperso-orange.fr/sebastien.godard/
Summary     : Sar and Iostat Commands for Linux
Description :
Sar and Iostat commands for Linux. The sar command collects and reports
system activity information. The iostat command reports CPU statistics
and I/O statistics for TTY devices and disks.  The information
collected by sar and iostat can be saved in a binary file for future
inspection. Both commands now support SMP machines when displaying CPU
utilization.
Distribution: SUSE Linux Enterprise 15

DL380G9H44U37:/etc/systemd/system #  cat /usr/lib/systemd/system/sysstat.service
[Unit]
Description=Write information about system start to sysstat log
After=remote-fs.target local-fs.target
Before=cron.service

[Service]
Type=oneshot
ExecStart=/usr/lib64/sa/sa1  --boot
ExecStart=/bin/ln -fs /etc/sysstat/sysstat.cron /etc/cron.d/sysstat
ExecStop=/bin/rm -f /etc/cron.d/sysstat
StandardOutput=null
RemainAfterExit=true
[Install]
WantedBy=multi-user.target

# BUT, this file does absolutely nothing until "systemctl enable sysstat" is executed, this command creating a link to the file above such that it is executed after a system restart.

DL380G9H44U37:/mnt/OS_and_Apps/SUSE/SLES15/x86_64 # systemctl status sysstat
● sysstat.service - Write information about system start to sysstat log
   Loaded: loaded (/usr/lib/systemd/system/sysstat.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

# Confirmation that the service is disabled in the above output

# Now enabling the service which creates the link
DL380G9H44U37:/etc/systemd/system # systemctl enable sysstat
Created symlink /etc/systemd/system/multi-user.target.wants/sysstat.service → /usr/lib/systemd/system/sysstat.service.

# After reboot

DL380G9H44U37:~ # service sysstat status
● sysstat.service - Write information about system start to sysstat log
   Loaded: loaded (/usr/lib/systemd/system/sysstat.service; enabled; vendor preset: disabled)
   Active: active (exited) since Fri 2018-09-07 07:48:38 EDT; 5min ago
  Process: 2344 ExecStart=/bin/ln -fs /etc/sysstat/sysstat.cron /etc/cron.d/sysstat (code=exited, status=0/SUCCESS)
  Process: 2318 ExecStart=/usr/lib64/sa/sa1 --boot (code=exited, status=0/SUCCESS)
 Main PID: 2344 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 7372)
   CGroup: /system.slice/sysstat.service

Sep 07 07:48:38 DL380G9H44U37 systemd[1]: Starting Write information about system start to sysstat log...
Sep 07 07:48:38 DL380G9H44U37 systemd[1]: Started Write information about system start to sysstat log.

# The same output is also available via service sysstat status

# Prior to enabling
DL380G9H44U37:/etc/systemd/system # service sysstat status
● sysstat.service - Write information about system start to sysstat log
   Loaded: loaded (/usr/lib/systemd/system/sysstat.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
# After enabling but prior to reboot
DL380G9H44U37:/etc/systemd/system # service sysstat status
● sysstat.service - Write information about system start to sysstat log
   Loaded: loaded (/usr/lib/systemd/system/sysstat.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
# After reboot
DL380G9H44U37:~ # systemctl status sysstat
● sysstat.service - Write information about system start to sysstat log
   Loaded: loaded (/usr/lib/systemd/system/sysstat.service; enabled; vendor preset: disabled)
   Active: active (exited) since Fri 2018-09-07 07:48:38 EDT; 5min ago
  Process: 2344 ExecStart=/bin/ln -fs /etc/sysstat/sysstat.cron /etc/cron.d/sysstat (code=exited, status=0/SUCCESS)
  Process: 2318 ExecStart=/usr/lib64/sa/sa1 --boot (code=exited, status=0/SUCCESS)
 Main PID: 2344 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 7372)
   CGroup: /system.slice/sysstat.service

Sep 07 07:48:38 DL380G9H44U37 systemd[1]: Starting Write information about system start to sysstat log...
Sep 07 07:48:38 DL380G9H44U37 systemd[1]: Started Write information about system start to sysstat log

# And sure enough, the /etc/cron.d/sysstat entry now exists (after the reboot)

DL380G9H44U37:~ # ll /etc/cron.d/sysstat
lrwxrwxrwx 1 root root 25 Sep  7 07:48 /etc/cron.d/sysstat -> /etc/sysstat/sysstat.cron
DL380G9H44U37:~ #
DL380G9H44U37:~ # cat /etc/cron.d/sysstat
# crontab for sysstat

# Activity reports every 10 minutes everyday
*/10 * * * * root [ -x /usr/lib64/sa/sa1 ] && exec /usr/lib64/sa/sa1 -S ALL 1 1

# Update reports every 6 hours
55 5,11,17,23 * * *     root [ -x /usr/lib64/sa/sa2 ] && exec /usr/lib64/sa/sa2 -A

# And the sar  -P ALL output contains the LINUX RESTART message as it HAS to following a system reboot.

DL380G9H44U37:~ # sar -P ALL
Linux 4.12.14-23-default (DL380G9H44U37)        09/07/18        _x86_64_        (48 CPU)

07:48:38     LINUX RESTART      (48 CPU)

07:50:01        CPU     %user     %nice   %system   %iowait    %steal     %idle
08:00:01        all      0.04      0.00      0.13      0.65      0.00     99.19
08:00:01          0      0.00      0.00      0.00      0.00      0.00    100.00
08:00:01          1      0.00      0.00      0.00      0.00      0.00    100.00
08:00:01          2      0.00      0.00      0.00      0.00      0.00    100.00
08:00:01          3      0.00      0.00      0.00      0.00      0.00    100.00
08:00:01          4      0.00      0.00      0.00      0.00      0.00     99.99
08:00:01          5      0.01      0.00      0.00      0.00      0.00     99.99
08:00:01          6      0.00      0.00      0.00      0.00      0.00    100.00
08:00:01          7      0.00      0.00      0.00      0.00      0.00    100.00
08:00:01          8      0.00      0.00      0.01      0.00      0.00     99.99
08:00:01          9      0.00      0.00      0.00      0.00      0.00    100.00
08:00:01         10      0.00      0.00      0.00      0.00      0.00    100.00

# With no values exceeding 100.00 %
No doubt someone will be able to tell me why after installing a product critical requirements to allow the product to function correctly are not automatically applied during installation ?

Further, to some the above might seem really obvious, to others (including myself), the critical need to issue the command "systemctl enable sysstat" was missed. Personally I'd like to see the requirement to do this added to the sysstat documentation page.

Please proceed to close this Issue, 

Thanks

**Comment by sysstat** [comment]
Thanks Pete.

First you can decide to install sysstat but not to create logfiles (`/var/log/sa/saDD`). `sar` can be used interactively on the command line and create datafiles on the fly if needed (using its option -o).

Yet, most of the time, we install `sar` in order actually to create logfiles and get a global view of our sysstem. In this case we need to launch `sadc` (or its script `sa1`) periodically to get samples of the system counters and save them for future inspection. We also need to call `sadc` (with no "count" and "interval" parameters) at boot time to indicate a system restart and tell `sar` that kernel counters have restarted from zero so that it can calculate its statistics properly (I agree that this should be made clear in the documentation and there is probably some room for improvement here).
Now you have two ways to launch `sadc` periodically :
1) The preferred way (the first one used by sysstat when installed) is to use `systemd` and its unit files. If sysstat detects (at installation stage) that `systemd` is present on your system then it will install sysstat unit files and, if told to do so (e.g. `./configure --enable-install-cron`), it will also enable the unit files at system restart (it will add a call to `systemctl enable sysstat` at boot time when you enter `make install`).
2) The other way is to create a **crontab** entry (in `/etc/cron.d`, `/etc/cron.hourly`, `/etc/cron.daily`...) that will call `sadc` periodically. If `systemd` is **not** present and the user requested that sysstat creates its necessary cron entries (again with e.g. `./configure --enable-install-cron`), it will (when you enter `make install`) create those files in `/etc` and also add the link to call `sadc` at  boot time to insert a LINUX RESTART message in current log file.

Be aware that only **one** of those solutions (using `systemd` *or* using cron entries) should be used. Don't mix both of them as the results might be unexpected.
