### ISSUE TITLE
Superfluous use of "&" within cron job definitions

### ISSUE THREAD

**Issue by stevekay** [sysstat/sysstat#194]
As I understand it, such a suffix isn't needed by cron.  So where sysstat references commands such as:

    0 1-22 * * * /usr/local/lib/sa/sa1 600 6 &

...it's functionally identical to

    0 1-22 * * * /usr/local/lib/sa/sa1 600 6

So https://github.com/sysstat/sysstat/pull/193 created to remove unnecessary "&" entries.

**Comment by sysstat** [comment]
PR merged, closing issue.
