### ISSUE TITLE
Printer friendly color scheme for sadf

### ISSUE THREAD

**Issue by mgierlings** [sysstat/sysstat#205]
First of all let me say thanks for creating sysstat, it is a great tool set.

While I personally like the SVG ouput produced by sadf (colored graph on dark background), it is not really suitable for (black/white) printing. I checked the sadf man page and did a web search but didn't find any option to enable a "light-background-mode" for sadf. Does sadf currently offer any way to generate printer friendly SVGs?

If no such feature exists, recoloring the graphs using image editing software could be a workaround. However I think it would be useful, if there was a way to natively produce printer friendly output with sadf. What do you think?

**Comment by sysstat** [comment]
This is the end of the year, and Santa Claus may actually add this new feature to next sysstat version! :wink:

**Comment by mgierlings** [comment]
Nice, thank you Sebastien and Santa Claus of course =). Merry Christmas to you and the sysstat community.

**Comment by sysstat** [comment]
Commit d18e78c enables the user to select a different color palette for sadf SVG output, using a new option "customcol":
``sadf -g -O customcol (...)``
I'm not sure that this new palette is really printer friendly (though it is intended to be), so please test it and tell me which colors should be changed so that it can be printer friendly by default.
Here is a sample output:

![image](https://user-images.githubusercontent.com/4254780/51043118-2cbc0580-15be-11e9-9c59-520886aa7240.png)

Anyway this new palette will be fully customizable be the user (patches to come soon) so everybody should be able to find the right match for his need.

**Comment by mgierlings** [comment]
Thanks for the update. I think I'd definitely use a white background for the default printer scheme. I also converted your image to grey scale, to see how it would look on a non color printer here is the result
![greyscale](https://user-images.githubusercontent.com/17745673/51075638-81c74c80-168e-11e9-9ce6-364ee5a8f826.png)

(%usr, %guest, %gnice); (%steal, %iowait) and (%nice, %soft) are really hard to distinguish.

I found [this post](https://graphicdesign.stackexchange.com/a/70545) on graphicdesign stackexchange pretty helpful. It seems that picking the following colors from the bottom palette, plus black and white, might do the trick:

- black  (`#000000`)
- the dark blue (circle 7) (`#1A1AFF`)
- one purpleish tone (i.e. circle 8), (i.e. `#B21AFF`)
- the red (circle 1, might need some tweaking if it is too similar to the purple) (`#FF1A1A`) 
- the light blue (circle 6)  (`#1AB2FF`)
- one darker greenish tone (circles 4, 5) (i.e. `#1AFFB2`)
- the orange (circle 2)  (`#FFB31A`)
- the light green (circle 3) (`#B2FF1A`)
- white  (`#FFFFFF`)

**Comment by sysstat** [comment]
Commit 87320de adds a new black and white palette. I still think that some colors are hard to distinguish.
I also modified the default colors used by the custom palette to match your colors above (see commit 4cd46fa). One color (used for %gnice) is almost white and hardly visible though.
Sample outputs:

Black and white palette ("`sadf -g -O bwcol (...)`"):
![image](https://user-images.githubusercontent.com/4254780/51083903-ed0e2e80-1721-11e9-98c4-14d2e47a5565.png)

Custom palette with updated colors ("`sadf -g -O customcol (...)`"):
![image](https://user-images.githubusercontent.com/4254780/51083923-2a72bc00-1722-11e9-8bb6-cf8133eedec3.png)

And the default palette ("`sadf -g (...)`"):
![image](https://user-images.githubusercontent.com/4254780/51083936-5beb8780-1722-11e9-94ed-486a1ef32d53.png)

**Comment by mgierlings** [comment]
This looks very good to me, thank you for the effort. I think there is only so much we can do with grey scale. For many occasions it will be sufficient to use less then nine graphs in a single chart so the barely readable light grey should not become a problem too often.
