### ISSUE TITLE
sadc triggers mount of all autofs filesystems

### ISSUE THREAD

**Issue by robberteggermont** [sysstat/sysstat#213]
sysstat version 10.1.5 (RHEL7.6)
/usr/lib64/sa/sadc -F -L -S DISK 1 1 - (called as '/usr/lib64/sa/sa1 1 1' from /etc/cron.d/sysstat)

We have over a 1000(!) autofs entries for nfs shares. For every run of sadc, all autofs entries are mounted. While the autofs entries are mounted (which takes over 2 minutes), sadc remains in the 'autofs4_wait' state.

Is there a workaround to prevent sadc from scanning autofs mounts?
If not, has this already been fixed in a newer version of sysstat?
If not, is it possible to modify sadc to exclude autofs entries?

**Comment by sysstat** [comment]
I'm currently working on a fix that will be included in next sysstat version.
See also PR #210 and #211 (but they need to be modified though).

**Comment by robberteggermont** [comment]
Thanks, I missed those PRs but they are indeed about this same problem.

**Comment by sysstat** [comment]
Commit 802106b merged the fix that makes sar/sadc ignore autofs entries in /etc/mtab.
Tell me if things are OK for you now.
