### ISSUE TITLE
mpstat:  the json output "-1" instead of "all" to indicate average statistics

### ISSUE THREAD

**Issue by songha1x** [sysstat/sysstat#214]
Sysstat version 12.1.2
Issue description: 
        Run mpstat output with json, shown keywords "-1" for average statistics. It should be changed to "all".

Command-1: mpstat 1
Output:

> 05:27:48 PM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
> 05:27:49 PM  all    2.25    0.00    0.50    0.00    0.00    0.00    0.00    0.00    0.00   97.25
> 05:27:50 PM  all    0.75    0.00    0.75    0.00    0.00    0.00    0.00    0.00    0.00   98.50
> 05:27:51 PM  all    1.50    0.00    0.25    0.25    0.00    0.00    0.00    0.00    0.00   97.99
> 

Command-2: mpstat 1 -o JSON
Output:

>			"statistics": [
>				{
>					"timestamp": "05:30:56 PM",
>					"cpu-load": [
>						{"cpu": "-1", "usr": 1.01, "nice": 0.00, "sys": 0.50, "iowait": 0.00, "irq": 0.00, >"soft": 0.00, "steal": 0.00, "guest": 0.00, "gnice": 0.00, "idle": 98.49}
>					]
>				},
>				{
>					"timestamp": "05:30:57 PM",
>					"cpu-load": [
>						{"cpu": "-1", "usr": 1.51, "nice": 0.00, "sys": 0.50, "iowait": 0.00, "irq": 0.00, >"soft": 0.00, "steal": 0.00, "guest": 0.00, "gnice": 0.00, "idle": 97.99}
>					]

**Comment by sysstat** [comment]
You're right. Fixed.
Thank you.
