### ISSUE TITLE
Overrule hard coded umask setting in sa1 and sa2

### ISSUE THREAD

**Issue by danny-smit** [sysstat/sysstat#217]
Hi,

I'm trying to make systems adhere to security benchmarks like the CIS benchmark. One of the benchmark items describes to ensure that no files in /var/log/ are world-readable, which can be achieved by setting the default umask to 027.

Unfortunately the sa1 and sa2 script have hardcoded umasks which overrules the default umask setting. Currently the only way to get around that seems to be to patch those scripts, but that is very inconvenience in case the package is updated.

Would it be possible to add an configuration option to overrule the hardcoded umask? 

I'm aware that that will have impact on the usability of some commands, but that can be resolved by properly configuring users and groups instead.

**Comment by stevekay** [comment]
Offending lines are https://github.com/sysstat/sysstat/blob/master/sa1.in#L15 and 
https://github.com/sysstat/sysstat/blob/master/sa2.in#L9

**Comment by sysstat** [comment]
Yes, this is exactly the solution that we need: Add a new variable in `sysstat.sysconfig.in` specifying the mask that will be read and used by sa1 and sa2.

**Comment by danny-smit** [comment]
@stevekay Thanks for the suggestion, that might work in this case. However, I'm always a bit reserved  on including shell-like construct in sysconfig files, as in general I can't be sure if there are non-shell commands of which I'm unaware that are also reading its content.

@sysstat Do you want me to create a pull request for that?

**Comment by sysstat** [comment]
@danny-smit yes, please send me a PR.
