### ISSUE TITLE
Maybe just misprint in options for iostat

### ISSUE THREAD

**Issue by boput** [sysstat/sysstat#219]
Translating sysstat (this is not an issue, just a question)

"info iostat" gives this possible option (truncated, shown only for "device"):
device [,...]

but latest sysstat.pot file lists this options as (truncated, shown only for "device"):
[ <device> [...]

The only difference is "," in the info display. Which is correct?

**Comment by sysstat** [comment]
There is probably a confusion:
* devices following option -p should actually be comma-separated
* other devices should not.

So if you enter for example `iostat -p sda,sdb sdc sdd` then you will get statistics for
* sda device and all its partitions
* sdb device and all its partitions
* sdc device
* sdd device
This is what the manual page and the usage message say:
```
$ iostat -?
Usage: iostat [ options ] [ <interval> [ <count> ] ]
Options are:
<SNIP>
[ -p [ <device> [,...] | ALL ] ]
[ <device> [...] | ALL ]
```

**Comment by boput** [comment]
It is clear now.

Thank you
