### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by namepunk** [sysstat/sysstat#222]
iostat -ydx 2 1 /dev/sdc -o JSON produces an output that is not a valid JSON. 

> `{"sysstat": {
>         "hosts": [
>                 {
>                         "nodename": "nodename",
>                         "sysname": "Linux",
>                         "release": "4.9.0-8-amd64",
>                         "machine": "x86_64",
>                         "number-of-cpus": 12,
>                         "date": "04/23/2019",
>                         "statistics": [
> ,
>                                 {
>                                         "disk": [
>                                                 {"disk_device": "sdc", "r/s": 282.50, "w/s": 4.50, "d/s": 0.00, "rkB/s": 70208.00, "wkB/s": 2720.00, "dkB/s": 0.00, "rrqm/s": 30.00, "wrqm/s": 335.00, "drqm/s": 0.00, "rrqm": 9.60, "wrqm": 98.67, "drqm": 0.00, "r_await": 38.03, "w_await": 44.44, "d_await": 0.00, "rareq-sz": 124.26, "wareq-sz": 302.22, "dareq-sz": 0.00, "aqu-sz": 11.14, "util": 100.00}
>                                         ]
>                                 }
>                         ]
>                 }
>         ]
> }}`

comma in statistics 
`iostat -V
sysstat version 12.1.4
(C) Sebastien Godard (sysstat <at> orange.fr)
`
i find same issue https://github.com/sysstat/sysstat/issues/163, it closed, but problem is already present

**Comment by sysstat** [comment]
Thanks for this bug report. Will investigate it ASAP.
