### ISSUE TITLE
mpstat stuck at pause()

### ISSUE THREAD

**Issue by frank0718** [sysstat/sysstat#223]
in my machine , use   mpstat 1 2  
just stuck at pause()... 
```
 here is the ltrace output 
memcpy(0x22aaf60, "\354\306y\037\004", 7056)                              = 0x22aaf60
memcpy(0x22acb00, "", 784)                                                = 0x22acb00
memcpy(0x7f0d37db8010, "", 142100)                                        = 0x7f0d37db8010
pause(0x7f0d37ddab24, 0x7f0d37e20b24, 0, 0, 0 <unfinished ...>
--- SIGINT (Interrupt) ---
+++ killed by SIGINT +++
```
i have to ctrl + c to stop . 

i switch to root, it just works .

the sysstat version is sysstat-9.0.4-33el6_9.1.x86_64

**Comment by sysstat** [comment]
Hmm, probably not a bug directly linked to sysstat itself.
mpstat, like any other sysstat commands, doesn't need root privileges to run.
Also please consider upgrading your sysstat version since 9.0.4 is quite old (10 years old).
