### ISSUE TITLE
[RFE] Add Node,Socket,Core data to mpstat output

### ISSUE THREAD

**Issue by mcaleavya** [sysstat/sysstat#225]
Hi 

would it be possible to add the numa node, socket and core to the output of mpstat. As an example.

10:29:50     NODE   SOCK   CORE   CPU    %usr     %nice    %sys     %iowait  %irq     %soft    %steal   %guest   %gnice   %idle
10:29:51                          all    2.17     0.00     0.29     0.04     0.00     0.08     0.00     0.00     0.00     97.41
10:29:51     0      0      0      0      35.00    0.00     2.00     1.00     0.00     1.00     0.00     0.00     0.00     61.00
10:29:51     0      0      1      1      5.05     0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     94.95
10:29:51     0      0      2      2      0.00     0.00     1.00     0.00     0.00     0.00     0.00     0.00     0.00     99.00
10:29:51     0      0      3      3      0.99     0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     99.01
10:29:51     0      0      4      4      1.01     0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     98.99
10:29:51     0      0      5      5      1.00     0.00     2.00     0.00     0.00     0.00     0.00     0.00     0.00     97.00
10:29:51     1      1      6      6      0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     100.00
10:29:51     1      1      7      7      0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     100.00
10:29:51     1      1      8      8      0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     100.00
10:29:51     1      1      9      9      0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     100.00
10:29:51     1      1      10     10     0.99     0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     99.01
10:29:51     1      1      11     11     0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     0.00     100.00

This allows us to see what cores are busy and map busy CPUs to specific nodes/sockets etc.

**Comment by sysstat** [comment]
Sorry, this is not what I know the best, but where do you find these information in the {/proc,/sys} directories?

**Comment by mcaleavya** [comment]
Hi 

We already have the Node data which is is good, socket is straight forward read from physical_package_id. Core however was an issue as I thought originally that it would have just been core_id but that's different from what lscpu shows. I looked a the lscpu code but got a tad lost when it was parsing into a bitmap. Taking a look at the data however I have the following script which looks correct in regards to the lscpu -p data.

I have tested this script against the lscpu data and it looks correct on a small server and a large 4 numa node box. 

for i in {0..95}
do
CPU=$i
CORE=`awk -F, '{print $1}' /sys/bus/cpu/devices/cpu${i}/topology/thread_siblings_list`
SOCK=`cat /sys/bus/cpu/devices/cpu${i}/topology/physical_package_id`
NODE=`ls -d /sys/bus/cpu/devices/cpu${i}/node* |sed 's/\// /g; s'/node//g |awk '{print $NF}'`
echo "$CPU,$CORE,$SOCK,$NODE"
done


Looking at the coreid when we have hyper threads its the first entry in the thread_siblings_list i.e. 
bash-4.2$ lscpu -p=CPU,CORE,SOCKET,NODE |grep 41
CPU,Core,Socket,Node
41,41,3,3
89,41,3,3


bash-4.2$ cat /sys/bus/cpu/devices/cpu41/topology/thread_siblings_list
41,89
bash-4.2$ cat /sys/bus/cpu/devices/cpu89/topology/thread_siblings_list
41,89

so lscpu gives the core as 41 however the core_id file has 9 
bash-4.2$ cat /sys/bus/cpu/devices/cpu89/topology/core_id
9
bash-4.2$ cat /sys/bus/cpu/devices/cpu41/topology/core_id
9

**Comment by sysstat** [comment]
Thanks. It seems that I have all I need to add this feature.
I will probably add a new switch so that these new fields (CORE,SOCKET,NODE) appear in the CPU-based output (mpstat -P), not the NUMA-based one (mpstat -N).
