### ISSUE TITLE
Wrong values after converting binary output to newer version

### ISSUE THREAD

**Issue by blastmaster** [sysstat/sysstat#227]
Hi,
I've recorded some `sar` statistics with `sar -r 1 -o sar-mem.out` on our cluster (sysstat version 10.1.5).
Then I copied the output file to my local machine (sysstat version 12.0.3), after `sar` was complaining about the format, I converted the output with `sadf -c sar-mem.out > sar-mem-new.out`.
Everything seems to be fine.
But if I try to open the new file with `sar -r -f sar-mem-new.out` I get wrong values.

```
$ sar -r 1 5 -f sar-mem-new.out
Linux 3.10.0-862.14.4.el7.x86_64 (taurusnvme16)         06/18/19        _x86_64_        (32 CPU)

11:16:13    kbmemfree   kbavail kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
11:16:14       424160         0  10608952     16.22   9470884  44911076  13058168     17.70  14973136  45360064        32
11:16:15       425740         0  10607344     16.22   9470884  44911104  13058168     17.70  14973008  45360076        60
11:16:16       426092         0  10606964     16.21   9470884  44911132  13058168     17.70  14973048  45360088        88
11:16:17       425844         0  10607184     16.22   9470884  44911160  13058168     17.70  14973040  45360100       116
11:16:18       426040         0  10606960     16.21   9470884  44911188  13058168     17.70  14973120  45360112       144
Average:       425575         0  10607481     16.22   9470884  44911132  13058168     17.70  14973070  45360088        88
``` 

If I do the output on the machine where I did the recording I get.
```
sar -r 1 5 -f sar-mem.out
Linux 3.10.0-862.14.4.el7.x86_64 (taurusnvme16)         06/18/19        _x86_64_        (32 CPU)

11:16:13    kbmemfree kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
11:16:14       424160  64990912     99.35   9470884  44911076  13058168     17.70  14973136  45360064        32
11:16:15       425740  64989332     99.35   9470884  44911104  13058168     17.70  14973008  45360076        60
11:16:16       426092  64988980     99.35   9470884  44911132  13058168     17.70  14973048  45360088        88
11:16:17       425844  64989228     99.35   9470884  44911160  13058168     17.70  14973040  45360100       116
11:16:18       426040  64989032     99.35   9470884  44911188  13058168     17.70  14973120  45360112       144
Average:       425575  64989497     99.35   9470884  44911132  13058168     17.70  14973070  45360088        88
```

As you can see the  `kbmemused` and `%memused` differs significantly.
After converting the `kbmemused` show just around 10GB of resource usage instead of around 64GB.
The `kbavail` section seems to be only available in the newer version, and is 0 which looks ok.
I can also reproduce this when using a freshly build sysstat version 12.1.5 for conversion and output.
I'am quite sure that the original values recorded are correct. So there might be an issue during conversion? Or did I do something wrong?

**Comment by sysstat** [comment]
Conversion works well :-)
But as of sysstat version 11.7.4, sar changed how the amount of used memory (kbmemused) is calculated to be consistent with the output of free(1) and top(1).
Before : it was calculated as "total amount of memory" - "kbmemfree", which was not really interesting, the amount of used memory being almost always close to 100%
Now : it is calculated as "total amount of memory" - "kbmemfree" - "kbbuffers" - "kbcached" - "kbslab" (see sar manual page). It gives a better idea of the memory which is really used.

**Comment by blastmaster** [comment]
Ohh well, yeah that makes sense. Thank you very much for the quick response.
