### ISSUE TITLE
Idea: Add kernel PSI counters

### ISSUE THREAD

**Issue by anayrat** [sysstat/sysstat#233]
Hi,

Since version [4.20, linux kernel](https://kernelnewbies.org/Linux_4.20#Pressure_stall_information_for_better_overview_of_system_load) can provide pressure-stall information that could be useful to provide performance information about CPU, IO and memory starvation.

It will be great to collect theses counters :)

Here are some inputs:

- [Tracking pressure-stall information](https://lwn.net/Articles/759781/)
- [Linux Pressure Stall Information (PSI) by Example](https://unixism.net/2019/08/linux-pressure-stall-information-psi-by-example/)
- [Getting Started with PSI](https://facebookmicrosites.github.io/psi/docs/overview)
- [PSI - Pressure Stall Information - Kernel's documentation](https://www.kernel.org/doc/html/latest/_sources/accounting/psi.rst.txt)

Regards,

**Comment by sysstat** [comment]
Hi,
I actually had in mind to add these metrics to `sar` in a future sysstat version.
But please don't be in too much of a hurry as I don't have much time for this now.
Regards

**Comment by anayrat** [comment]
Well, don't worry, I opened the issue just to think about it :)
Thanks

**Comment by MrPippin66** [comment]
I concur I'd like to see this. Though relatively new a couple of years ago, this is now pretty much a standard function in all current Linux distributions.

I add my vote to including this.
