### ISSUE TITLE
 Shaky bandwidth with 'sar dev -n 1' but stable by reading rx via ifconfig 

### ISSUE THREAD

**Issue by Whishay** [sysstat/sysstat#236]
Recently I got an issue with sar when trying to observe the bandwidth on an interface.

Two hosts connected back to back
Debian 9.9
Kernel 4.14
Run kernel pktgen from one to the other,  only a thread with a udp connection(a queue in the NIC).

The bandwidth goes down from 1.5M to 1.2M(around 20%) every 10 seconds like this, but if I read
the RX packets from ifconfig and there is no problem with that, anyone can help have a look.

The scripts read ifconfig output:
#!/bin/bash
old=0
new=0
while true 
do
	new=$(ethtool   -S eth0 |  grep rx10_pack | awk '{print $2}')
	rx=`expr $new - $old`
	echo Rx: $rx New: $new, Old: $old 
	old=$new
	sleep 1
done

Bandwidth:
Rx: 1521601 New: 1392613942, Old: 1391092341
Rx: 1534852 New: 1394148794, Old: 1392613942
Rx: 1521613 New: 1395670407, Old: 1394148794
Rx: 1524741 New: 1397195148, Old: 1395670407
Rx: 1527266 New: 1398722414, Old: 1397195148
Rx: 1529720 New: 1400252134, Old: 1398722414
Rx: 1530025 New: 1401782159, Old: 1400252134
Rx: 1531550 New: 1403313709, Old: 1401782159
Rx: 1527692 New: 1404841401, Old: 1403313709
Rx: 1529809 New: 1406371210, Old: 1404841401
Rx: 1532232 New: 1407903442, Old: 1406371210
Rx: 1526633 New: 1409430075, Old: 1407903442
Rx: 1544124 New: 1410974199, Old: 1409430075
Rx: 1508854 New: 1412483053, Old: 1410974199
Rx: 1528849 New: 1414011902, Old: 1412483053
Rx: 1536701 New: 1415548603, Old: 1414011902
Rx: 1529026 New: 1417077629, Old: 1415548603
Rx: 1529131 New: 1418606760, Old: 1417077629
Rx: 1525529 New: 1420132289, Old: 1418606760

Sar:
06:55:08 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:09 PM      eth0 1552224.00     12.00  90950.90      2.91      0.00      0.00      0.00      2.98

06:55:09 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:10 PM      eth0 1557665.00     17.00  91270.00      2.51      0.00      0.00      0.00      2.99

06:55:10 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:11 PM      eth0 1555888.00     57.00  91267.47      6.46      0.00      0.00      0.00      2.99

06:55:11 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:12 PM      eth0 1542538.00     87.00  90384.89      8.92      0.00      0.00      0.00      2.96

06:55:12 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:13 PM      eth0 1548540.00     23.00  90735.86      2.66      0.00      0.00      0.00      2.97

06:55:13 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:14 PM      eth0 1242007.00      9.00  72773.89      1.46      0.00      0.00      0.00      2.38

06:55:14 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:15 PM      eth0 1554147.00     10.00  91063.35      1.50      0.00      0.00      0.00      2.98

06:55:15 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:16 PM      eth0 1559384.00     30.00  91370.80     19.96      0.00      0.00      0.00      2.99

06:55:16 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:17 PM      eth0 1549069.00     15.00  90766.06      2.03      0.00      0.00      0.00      2.97

06:55:17 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:18 PM      eth0 1542547.00      9.00  90383.85      1.42      0.00      0.00      1.00      2.96

06:55:18 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:19 PM      eth0 1554148.00     14.00  91063.77      2.18      0.00      0.00      0.00      2.98

06:55:19 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:20 PM      eth0 1549974.00     11.00  90818.90      1.62      0.00      0.00      0.00      2.98

06:55:20 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:21 PM      eth0 1549147.00     26.00  90771.09      5.36      0.00      0.00      0.00      2.97

06:55:21 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
06:55:22 PM      eth0 1242518.00     87.00  72806.25     10.32      0.00      0.00      0.00      2.39

**Comment by sysstat** [comment]
Try to use `/proc/net/dev` file instead of ethtool as this is what sar uses to collect its statistics, i.e.:
```
new=$(cat /proc/net/dev | grep eth0 | awk '{print $2}')
```
Also save sar data into a file (with a command like `sar -o datafile -n DEV 1`) and attach the resulting file so that I can check which values are saved by sar (which should be the same as those displayed by your script).

**Comment by Whishay** [comment]
It seems /proc/net/dev doesn't calculate the statistics correctly.
Can't save the sar to a file with '-o' option.

/proc/net/dev Rx: 201602 New: 19831403848, Old: 19831202246
/proc/net/dev Rx: 252046 New: 19831655894, Old: 19831403848
/proc/net/dev Rx: 254001 New: 19831909895, Old: 19831655894
/proc/net/dev Rx: 253010 New: 19832162905, Old: 19831909895
/proc/net/dev Rx: 253222 New: 19832416127, Old: 19832162905
/proc/net/dev Rx: 253331 New: 19832669458, Old: 19832416127
/proc/net/dev Rx: 254101 New: 19832923559, Old: 19832669458
/proc/net/dev Rx: 252270 New: 19833175829, Old: 19832923559
/proc/net/dev Rx: 256659 New: 19833432488, Old: 19833175829
/proc/net/dev Rx: 260268 New: 19833692756, Old: 19833432488
/proc/net/dev Rx: 260087 New: 19833952843, Old: 19833692756
/proc/net/dev Rx: 261899 New: 19834214742, Old: 19833952843
/proc/net/dev Rx: 207618 New: 19834422360, Old: 19834214742
/proc/net/dev Rx: 259841 New: 19834682201, Old: 19834422360
/proc/net/dev Rx: 261028 New: 19834943229, Old: 19834682201
/proc/net/dev Rx: 259637 New: 19835202866, Old: 19834943229
/proc/net/dev Rx: 259872 New: 19835462738, Old: 19835202866
/proc/net/dev Rx: 259976 New: 19835722714, Old: 19835462738
/proc/net/dev Rx: 259473 New: 19835982187, Old: 19835722714
/proc/net/dev Rx: 258590 New: 19836240777, Old: 19835982187
/proc/net/dev Rx: 258184 New: 19836498961, Old: 19836240777
/proc/net/dev Rx: 258069 New: 19836757030, Old: 19836498961
/proc/net/dev Rx: 257788 New: 19837014818, Old: 19836757030
/proc/net/dev Rx: 258229 New: 19837273047, Old: 19837014818
/proc/net/dev Rx: 208125 New: 19837481172, Old: 19837273047


Ethtool -S:

ethtool -S Rx: 239233 New: 1634440521, Old: 1634201288
ethtool -S Rx: 239100 New: 1634679621, Old: 1634440521
ethtool -S Rx: 239874 New: 1634919495, Old: 1634679621
ethtool -S Rx: 239116 New: 1635158611, Old: 1634919495
ethtool -S Rx: 239355 New: 1635397966, Old: 1635158611
ethtool -S Rx: 238342 New: 1635636308, Old: 1635397966
ethtool -S Rx: 238330 New: 1635874638, Old: 1635636308
ethtool -S Rx: 238470 New: 1636113108, Old: 1635874638
ethtool -S Rx: 238877 New: 1636351985, Old: 1636113108
ethtool -S Rx: 238558 New: 1636590543, Old: 1636351985
ethtool -S Rx: 238339 New: 1636828882, Old: 1636590543
ethtool -S Rx: 238628 New: 1637067510, Old: 1636828882
ethtool -S Rx: 238812 New: 1637306322, Old: 1637067510
ethtool -S Rx: 238992 New: 1637545314, Old: 1637306322
ethtool -S Rx: 238952 New: 1637784266, Old: 1637545314
ethtool -S Rx: 236808 New: 1638021074, Old: 1637784266
ethtool -S Rx: 238851 New: 1638259925, Old: 1638021074
ethtool -S Rx: 238295 New: 1638498220, Old: 1638259925
ethtool -S Rx: 238540 New: 1638736760, Old: 1638498220
ethtool -S Rx: 238762 New: 1638975522, Old: 1638736760
ethtool -S Rx: 238901 New: 1639214423, Old: 1638975522
ethtool -S Rx: 238590 New: 1639453013, Old: 1639214423

**Comment by sysstat** [comment]
I'm more confident with /proc/net/dev (which is a direct access to the kernel counters) than with any other tools ;-)
And which version of sysstat are you using? "sar -o datafile" should work! Tell exactly what you enter on the command line.
