### ISSUE TITLE
New disk flush count/time statistics in linux 5.5+

### ISSUE THREAD

**Issue by koct9i** [sysstat/sysstat#240]
Patch already merged, but kernel at early stage and not released yet.
See https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b6866318657717c8914673a6394894d12bc9ff5e

I'll make patch for sysstat after week vacation if nobody make this before me.
Should be pretty trivial.

**Comment by sysstat** [comment]
Thanks. Your patch will be welcome. Don't forget to update iostat manual page too.
And don't worry too much here about non regression tests run through Travis CI that will probably fail...
