### ISSUE TITLE
Is iostat %util computed correctly?

### ISSUE THREAD

**Issue by Love-Kitty** [sysstat/sysstat#244]
iostat compute %util using function "compute_ext_disk_stats" in rd_stat.c 369

void compute_ext_disk_stats(struct stats_disk *sdc, struct stats_disk *sdp, unsigned long long itv, struct ext_disk_stats *xds)
{
  xds->util  = S_VALUE(sdp->tot_ticks, sdc->tot_ticks, itv);
   ...
}

But I found that tot_ticks measure i/o times in milliseconds
itv measure time difference in centi-seconds(1/100 sec)

Is there any modification of metric before call compute_ext_disk_stats?

**Comment by sysstat** [comment]
xds->util is always divided by 10 before being displayed. Hence %util doesn't correspond to the contents of xds->util but to the contents of xds->util / 10.
