### ISSUE TITLE
the Unit of networking measurement 

### ISSUE THREAD

**Issue by tlsalex** [sysstat/sysstat#249]
I am using sysstat plugin in telegraf. and get bellow result.

> network,device=eth0,host=fz coll_per_s=0,pct_ifutil=0,rxcmp_per_s=0,rxdrop_per_s=0,rxerr_per_s=0,rxfifo_per_s=0,rxfram_per_s=0,**rxkB**_per_s=0.05,rxmcst_per_s=0,rxpck_per_s=1,txcarr_per_s=0,txcmp_per_s=0,txdrop_per_s=0,txerr_per_s=0,txfifo_per_s=0,**txkB**_per_s=0,txpck_per_s=0 1580529158000000000

I wan to confirm the units used here (kB =1000bytes or 1024bytes) , it is Binary prefix unit or Decimal prefix unit ?
like ifconfig in centos --
Since net-tools 1.60-4 ifconfig is printing byte counters and human readable counters with IEC 60027-2 units, So 1 KiB are 2^10 byte

**Comment by sysstat** [comment]
sysstat uses 1024 bytes for 1 kB.

**Comment by tlsalex** [comment]
thank you
