### ISSUE TITLE
SAR collects filesystem metrics multiple times for the same fs if listed more than once in /etc/mtab

### ISSUE THREAD

**Issue by shimile** [sysstat/sysstat#256]
In my use case, I use slave bind mounts to mount multiple paths from the same filesystem on top of another read-only root file system, to make some of the paths writable and persistent across system image upgrades (where the whole root fs is replaced but configuration shouldn't be).

This is a standard operating procedure that has existed for years: https://access.redhat.com/solutions/2196881

Unfortunately, every such mount, causes /etc/mtab and /proc/mounts to make the filesystem the bind mounts "originate" from, appear multiple times.

Other tools, such as 'df', identify this, and only display the relevant fs once. 

Unfortunately, SAR does not, and a data point is created for each "copy" of the slave bind mount; So for example if you have 30 such paths mounted, **every** single SAR filesystem data collection will generate... 30 **identical** entries for the same filesystem.

**Comment by sysstat** [comment]
Thanks for opening this issue.
Will fix it ASAP.
