### ISSUE TITLE
The sar tool looks at the data collected by sadc and shows that the number of times is inconsistent.

### ISSUE THREAD

**Issue by viikei** [sysstat/sysstat#267]
The sar tool looks at the data collected by sadc and shows that the number of times is inconsistent.
I want to count 5 times in 1 second, but only show 4 times
![xxx](https://user-images.githubusercontent.com/62841836/88908408-58a6e680-d249-11ea-9898-1bf41efdfd03.png)

**Comment by sysstat** [comment]
For **sadc**, `count` is the number of data samples collected.  
For **sar**, `count` is the number of records to display.
You need *two* samples to be able to compute and display *one* line of statistics over an interval of time.
