### ISSUE TITLE
Network card traffic count is abnormal

### ISSUE THREAD

**Issue by Jeff-liaojinfu** [sysstat/sysstat#269]
Statistics of network card traffic through sar, suddenly a huge value
Currently the node of k8s, running docker bridge and container
[root@k8s-node22 ~]$ sar -n DEV -f /var/log/sa/sa07 -s 19:05:00 -e 19:20:00|grep -e IFACE -e eth0
07:05:01 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s
07:06:01 PM      eth0   4064.77   2390.08    665.84    734.36      0.00      0.00    447.12
07:07:01 PM      eth0   3993.19   2161.95    639.67    622.60      0.00      0.00    443.66
07:08:01 PM      eth0   4364.88   2664.19    861.90    829.94      0.00      0.00    438.77
07:09:01 PM      eth0 1005924595.60 543474884.30 261775679.83 145245456.55      0.00      0.00 61384799.16
07:10:01 PM      eth0   4258.25   2538.32    685.03    788.50      0.00      0.00    444.41
07:11:01 PM      eth0   4063.72   2254.73    637.27    662.77      0.00      0.00    442.16
07:12:01 PM      eth0   4056.63   2256.63    624.89    650.96      0.00      0.00    441.25
07:13:01 PM      eth0   4074.18   2138.71    657.04    643.36      0.00      0.00    444.37
07:14:01 PM      eth0   4023.64   2151.35    597.67    654.37      0.00      0.00    438.50
07:15:01 PM      eth0   4309.12   2172.77    681.45    657.93      0.00      0.00    440.28
07:16:01 PM      eth0   4414.30   2174.50    708.21    670.75      0.00      0.00    446.71
07:17:01 PM      eth0 1005456288.72 543221746.55 261652230.37 145178456.64      0.00      0.00 61357542.26
07:18:01 PM      eth0   4953.71   2792.39   1035.85    872.33      0.00      0.00    439.49
07:19:01 PM      eth0   5704.67   3784.16   1169.76   1276.82      0.00      0.00    439.84

**Is the statistics abnormal?**

**Comment by sysstat** [comment]
This is probably because the counters values have decreased. You can send me your sa07 binary datafile so that I can confirm this (sysstat at orange.fr).
