### ISSUE TITLE
Typo in the PHYS_PACK_ID (mpstat.h)

### ISSUE THREAD

**Issue by mikeBashStuff** [sysstat/sysstat#277]
The name of the sysfs attribute is incorrect: `topology/pysical_package_id` where it should be `topology/physical_package_id`. E.g.:
```
# [[ -e /sys/devices/system/cpu/cpu0/topology/physical_package_id ]]; echo $?
0
```
Noticed while strace'ing `mpstat` where `ENOENT`s popped up all of a sudden. :)

**Comment by sysstat** [comment]
Well spotted! Thanks :-)
