### ISSUE TITLE
Doc: sar -y TTY Device activity - xmtin vs txmtin

### ISSUE THREAD

**Issue by Pitterling** [sysstat/sysstat#278]
http://sebastien.godard.pagesperso-orange.fr/man_sar.html

xmtin/s 
Number of transmit interrupts per second for current serial line.

Documentation is about xmtin but should be txmtin ?
Can it be that this column was xmtin in the past and has been changed to txmtin? There is no commit having this change??

Thx

**Comment by sysstat** [comment]
Well spotted :-)
The metric's name is actually `xmtin` and not `txmtin`... I don't know how this typo got there.
Note that the name is correct in the output displayed by sadf (e.g. JSON or XML output).
