### ISSUE TITLE
Update the copied version of irqstat found in contrib/irqstat/irqstat

### ISSUE THREAD

**Issue by d1b** [sysstat/sysstat#283]
Hi, please update the copied version of irqstat found in [`contrib/irqstat/irqstat`](https://github.com/sysstat/sysstat/blob/master/contrib/irqstat/irqstat) - based upon/from https://github.com/lanceshelton/irqstat/blob/master/irqstat.

**Comment by sysstat** [comment]
Ok, I will do it ASAP. Thanks.
