### ISSUE TITLE
pidstat -R shows incorrect priority

### ISSUE THREAD

**Issue by myllynen** [sysstat/sysstat#293]
If top(1) is correct then it looks like `pidstat -R` displays process priority incorrectly:

```
# top -p 440253 -b -n 1 | grep -A 1 COMMAND
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 440253 root      20   0    4612   3736   2812 S   0.0   0.1   0:00.33 nano
# pidstat -R -p 440253 1 1 | grep -A 1 Command
13:32:50      UID       PID prio policy  Command
13:32:51        0    440253    0 NORMAL  nano
```

This is on Fedora 33 with procps-ng-3.3.16-2.fc33.x86_64 and sysstat-12.3.1-3.fc33.x86_64.

Thanks.

**Comment by sysstat** [comment]
Hi,
`top` displays the process' priority (15th numerical value after the process state in `/proc/#/stat` file, this is field `priority` in the kernel source) whereas `pidstat -R` displays the process' **real time** priority (37th numerical value, field `rt_priority`).

**Comment by myllynen** [comment]
Right, I missed that detail in the man page, thanks!
