### ISSUE TITLE
For single core machines, pidstat sometimes outputs that the total CPU utilization is higher than 100%

### ISSUE THREAD

**Issue by tongxiaoge1001** [sysstat/sysstat#295]
For single core machines, pidstat sometimes outputs that the total CPU utilization is higher than 100%. For multi-core machines, pidstat sometimes outputs more than  N * 100% CPU utilization ( N is number of cores). for example:
![图片](https://user-images.githubusercontent.com/85787453/121780859-ce534100-cbd4-11eb-929f-eff3fe623ed7.png)

We can use the code in https://github.com/sysstat/sysstat/issues/73#issuecomment-377221582 to reproduce the problem

eg .
gcc -pthread test.c
./a.out 10

Then open another window to monitor the CPU， eg.
pidstat 1 50

**Comment by tongxiaoge1001** [comment]
I tested in the latest version and the problem still exists. 
eg.
![图片](https://user-images.githubusercontent.com/85787453/121792290-8ad4f300-cc25-11eb-9f19-5138842d9469.png)

**Comment by tongxiaoge1001** [comment]
I use the top command to check the resource utilization of each process in the system， I find the same problem.
![图片](https://user-images.githubusercontent.com/85787453/121793128-a1cc1300-cc2e-11eb-834e-489853f09344.png)

**Comment by sysstat** [comment]
This shows that all tools are affected by the same issue. And obviously all of them didn't think this problem needed to be fixed. See #73 for the discussion.

**Comment by tongxiaoge1001** [comment]
ok, thanks.  I close the current issue.
