### ISSUE TITLE
iostat is missing option `--no-pretty`

### ISSUE THREAD

**Issue by mikkorantalainen** [sysstat/sysstat#299]
I have configured my system to use nice labels:

    $ ls /dev/disk/by-label
    backup  data  system

but when I run `/usr/bin/iostat -tmxy -j label backup -j label data -j label system 10` I get additional `--pretty` "by default". However, there doesn't seem to be any way to opt-out of this "default". As a result, I get output that looks like this:

```
$ /usr/bin/iostat -tmxy -j label backup -j label data -j label system 5
Linux 5.4.0-77-lowlatency (desktop) 	2021-07-07 	_x86_64_	(4 CPU)

2021-07-07 15:15:04
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           7.80    0.00    2.47    3.02    0.00   86.71

Device            r/s     w/s     rMB/s     wMB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
system
               187.60   14.80      4.67      0.08    14.00     3.40   6.94  18.68    0.37    0.36   0.02    25.48     5.51   0.44   8.90
data
                 0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
backup
                 0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00

```        
As you can imagine, those extra "pretty" linefeeds are not helping.

If you want to keep the logic that `-j` always forces `--pretty`, please, at least add `--no-pretty` to remove `I_D_PRETTY` from the actual binary flags used in the code. Unless I've understood the code incorrectly, there's no way to remove `I_D_PRETTY` once it has been added "by default".

If you don't want to add a feature to optionally remove pretty, the man page should be fixed to not speak about adding extra flags "by default" because that's not optional but forced.

**Comment by mikkorantalainen** [comment]
And I would expect that `-j label` usually has *short* labels and doesn't actually deserve `--pretty` by default in any case. I agree that `id`, `path` and `uuid` probably deserve `--pretty` in all cases because those are pretty long always.

**Comment by sysstat** [comment]
You are probably using an "old" version of iostat. Recent versions no longer add those linefeeds when option `-j` is used but instead move the label on the right side of the report. See example below (I don't have given a label to my disks but this is not important here):
```
$ iostat -V
sysstat version 12.5.4
(C) Sebastien Godard (sysstat <at> orange.fr)
$ iostat -d
Linux 5.12.13-200.fc33.x86_64 (localhost.localdomain) 	07/07/2021 	_x86_64_	(8 CPU)

Device             tps    kB_read/s    kB_wrtn/s    kB_dscd/s    kB_read    kB_wrtn    kB_dscd
dm-0             48.34       279.30       176.78         0.00     187156     118456          0
dm-1              0.22         3.79         0.02         0.00       2541         12          0
dm-2             20.36        84.35         0.02         0.00      56521         12          0
sda              89.64      2518.32       529.56         0.00    1687476     354845          0
sdb              37.46       381.08       175.64         0.00     255351     117696          0
sr0               0.00         0.00         0.00         0.00          0          0          0
zram0             0.49         1.95         0.01         0.00       1304          4          0
$ iostat -d -j label
Linux 5.12.13-200.fc33.x86_64 (localhost.localdomain) 	07/07/2021 	_x86_64_	(8 CPU)

      tps    kB_read/s    kB_wrtn/s    kB_dscd/s    kB_read    kB_wrtn    kB_dscd Device
    46.71       269.54       170.87         0.00     187156     118644          0 dm-0
     0.21         3.66         0.02         0.00       2541         12          0 dm-1
    19.65        81.40         0.02         0.00      56521         12          0 dm-2
    86.66      2430.26       511.99         0.00    1687476     355505          0 sda
    36.17       367.75       169.65         0.00     255351     117796          0 sdb
     0.00         0.00         0.00         0.00          0          0          0 sr0
     0.47         1.88         0.01         0.00       1304          4          0 zram0
```
Of course this applies for every keyword used with option `-j`:
```
$ iostat -d -j path
Linux 5.12.13-200.fc33.x86_64 (localhost.localdomain) 	07/07/2021 	_x86_64_	(8 CPU)

      tps    kB_read/s    kB_wrtn/s    kB_dscd/s    kB_read    kB_wrtn    kB_dscd Device
    35.73       203.41       131.37         0.00     187236     120920          0 dm-0
     0.16         2.76         0.01         0.00       2541         12          0 dm-1
    14.82        61.40         0.01         0.00      56521         12          0 dm-2
    65.71      1833.26       388.55         0.00    1687480     357657          0 pci-0000:04:00.0-ata-1
    27.55       277.50       130.41         0.00     255431     120036          0 pci-0000:04:00.0-ata-2
     0.00         0.00         0.00         0.00          0          0          0 pci-0000:03:00.4-usb-0:1:1.0-scsi-0:0:0:0
     0.36         1.42         0.00         0.00       1304          4          0 zram0

```

**Comment by mikkorantalainen** [comment]
$ iostat -V
iostat -txy -j label backup -j label data -j label system -V
**sysstat version 11.6.1**
(C) Sebastien Godard (sysstat <at> orange.fr)

This is the version distributed with Ubuntu 18.04 LTS. If this is fixed in more recent version, this issue can be closed.

**Comment by sysstat** [comment]
This issue has actually been fixed in current sysstat versions. So I close it now.

Wrt your other remark, you just have to tell `iostat` to use labels then all device names will be considered as labels (if the corresponding label is not found, the standard device name will be used). In your example, just enter :
```
iostat -txy -j label backup data system
```
