### ISSUE TITLE
Prefer `dpkg-reconfigure sysstat` to `/etc/default/sysstat`?

### ISSUE THREAD

**Issue by davidvandebunte** [sysstat/sysstat#309]
I'm a new user, so I apologize if this an uninformed question. I'm working on Ubuntu 20.04 and install `sysstat` with the command:
```
sudo apt-get install sysstat
```

The `sar` command reports an error unless data collecting is enabled. When I read the README.md in this repository, it says to set ENABLED="true" in `/etc/default/sysstat`. I mistakenly read this as `/etc/sysstat/sysstat` and was confused about why logging was not working, and why the ENABLED flag was not documented in `man sysstat`.

I eventually got it working by reading the `sa1` man page, which points to `/usr/share/doc/sysstat/README.Debian`, which explains how to run `dpkg-reconfigure sysstat` to enable monitoring.

I'm not sure why I misread the README.md (perhaps because I was already familiar with `/etc/sysstat/sysstat`) but it might help to point new users to `dpkg-reconfigure sysstat` in case somehow someone else makes the same mistake.

**Comment by sysstat** [comment]
I don't use Ubuntu so I didn't know `dpkg-reconfigure`. But commit a254dbf should probably answer the question.
