### ISSUE TITLE
pcp_def_percpu_int_metrics() breaks the build when not HAVE_PCP

### ISSUE THREAD

**Issue by mrmaximuzz** [sysstat/sysstat#310]
In the recent commit (6908bef2fcd3d5a2dee40e3bc3b563cc9ffc781a), a new `pcp_def_percpu_int_metrics` function has been added. However, it is not guarded by `#ifdef HAVE_PCP` check, which leads to a compilation failure (at least on my system) because of undeclared identifiers used in this function.

**Comment by mrmaximuzz** [comment]
I noticed that the `pcp_def_percpu_int_metrics` is called from `pcp_def_cpu_metrics`, and its body is already guarded by `HAVE_PCP` check. So I have just put the whole function under `HAVE_PCP` (to hide `pmInDom`), and it compiled just fine.

```diff
diff --git a/pcp_def_metrics.c b/pcp_def_metrics.c
index caabd97..852d9d3 100644
--- a/pcp_def_metrics.c
+++ b/pcp_def_metrics.c
@@ -40,6 +40,7 @@
  * @indom	PCP domain for interrupts metrics.
  ***************************************************************************
  */
+#ifdef HAVE_PCP
 void pcp_def_percpu_int_metrics(struct activity *a, pmInDom indom)
 {
 	int inst = 1;
@@ -60,6 +61,7 @@ void pcp_def_percpu_int_metrics(struct activity *a, pmInDom indom)
 		list = list->next;
 	}
 }
+#endif
 
 /*
  ***************************************************************************
```

**Comment by natoscott** [comment]
There's some other issues to resolve here too - @sysstat I've made a prototype fix, please take a look?  https://github.com/sysstat/sysstat/pull/311

In particular, I'm not sure how to iterate the IRQ line names while we're iterating CPUs ... can you look at this?  (the while loop in pcp_def_percpu_int_metrics may be iterating the wrong thing, or using the wrong name for IRQs?)  Thanks!

**Comment by sysstat** [comment]
@natoscott PR merged. Thank you (two problems have been fixed - See code review).
@mrmaximuzz Thanks for reporting this issue. This should now be fixed.

**Comment by natoscott** [comment]
> @natoscott PR merged. Thank you (two problems have been fixed - See code review).

Great - thanks!
