### ISSUE TITLE
Encoding problem in ubuntu 20

### ISSUE THREAD

**Issue by D0nVitalio** [sysstat/sysstat#321]
Hi. I guess smth is wrong. In 
root@vps:/var/log/sysstat# ls
sa26
root@vps:/var/log/sysstat# nano sa26
I get this:

  GNU nano 4.8                          sa26
��u!^L^B^@^@P^A^@^@^@^@^@^@^A^@^@^@^A^@^@^@^L^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@>
^@^@^@^@^@^@^@^@^@^@^@^B^@^@^@�^@^@^@^A^@^@^@^A^@^@^@^@^@^@^@^P^@^@^@^A^@^@^@^A>
�^Q^B^@^@^@^@@^Q^@^@^@^@^@^@��^@^@^@^@^@^@^@^@^@^@^@^@^@^@��^E^@^@^@^@^@^@^@^@^>
�^Q^B^@^@^@^@@^Q^@^@^@^@^@^@��^@^@^@^@^@^@^@^@^@^@^@^@^@^@��^E^@^@^@^@^@^@^@^

in vi editor this:
<96>Õu!^L^B^@^@P^A^@^@^@^@^@^@^A^@^@^@^A^@^@^@^L^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@m<92><8f>b^@^@^@^@d^@^@^@^@^@^@^@^B^@^@^@^P^@^@^@z^@^@^@^@^@^@^@^@^@^@^@  ^@^@^@^B^@^@^@^@^@^@^@^A^@^@^@$^@^@^@^X^@^@^@^@^@^@^@^Z^D^HLinux^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@vps.server.com^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@5.4.0-28-generic^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@x86_64^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@GMT^@^@^@^@^@^@^A^@^@^@<8b>^@^@^@^B^@^@^@^A^@^@^@^A^@^@^@P^@^@^@

How can I solve this?

**Comment by sysstat** [comment]
`saDD` files are binary files whose contents can be displayed with `sar -f saDD` and `sadf saDD` commands. Read `sar` and `sadf` manual pages to know which options are available to select activities or output formats.
