### ISSUE TITLE
Feature suggestion: able to repeat header every N lines when called from non-interactive terminal

### ISSUE THREAD

**Issue by mailinglists35** [sysstat/sysstat#332]
User reports \<some anomaly\> happened in the past on their workstation.
Support user logs on to read `sar` logs and system logs to investigate.

When reading daily `/var/log/sa/sarNN` report file created by `sa2` cron job, there are large number of lines for each category.

Categories begin with a useful header, but as the support user scrolls down, the column headers scroll up and exits the visible area, leaving the current viewport difficult to understand: "*what was the meaning of the third and fourth columns?* support scrolls up to find the headers then scroll down again to the investigating time lines"

A more confortable way to scroll through the report file would be that `sar` be able to repeat the header every 25th line, similarly to how `vmstat` command does. To prevent breaking third party tools and scripts that rely on a single line of headers when processing the logs, do not make the option default. Instead, the user should modify the cron/systemd-timer to enable this option. Hardcoding to 25 lines would be fine for me but maybe a customizable value would help others.

This seems to already happen automatically when output is an interactive terminal for `sar`, but apparently when called by `sa2`, the `sar` command only prints the headers once.

Thanks

**Comment by sysstat** [comment]
Maybe we could use an environment variable which would tell sar when the header has to be repeated when stdout is not a terminal, e.g.:
``
$ SA_REPEAT_HEADER=25 sar -f /var/log/sa/saDD > /var/log/sa/sarDD
``
(If you have a better idea for the variable name, tell me!)
If that variable is not set then header is not repeated (this is the current behavior).
