### ISSUE TITLE
pidstat do not report %usr %system correctly in SMP environment

### ISSUE THREAD

**Issue by liuyehcf** [sysstat/sysstat#344]
Someone has already report this bug in redhat, https://bugzilla.redhat.com/show_bug.cgi?id=1763579, but it is not resolved or responded yet.

## How to rebuild

```sh
cat /dev/zero | pigz -p 4 > /dev/null &
```

use option `-t` to show statistics of every thread, `pidstat -ut -p $(pgrep pigz)  1` outputs as below:
* process `pigz` has 6 threads
* total `%use` should be `1 + 30 + 100*4` = 431
* total `%system` should be `14 + 1 +1` = 16
* total `%CPU` should be `15+31+4*100` = 446

```
14时05分26秒   UID      TGID       TID    %usr %system  %guest    %CPU   CPU  Command
14时05分27秒  1010    219296         -  100.00   16.00    0.00  100.00     1  pigz
14时05分27秒  1010         -    219296    1.00   14.00    0.00   15.00     1  |__pigz
14时05分27秒  1010         -    219298   30.00    1.00    0.00   31.00    25  |__pigz
14时05分27秒  1010         -    219299  100.00    0.00    0.00  100.00    55  |__pigz
14时05分27秒  1010         -    219300  100.00    0.00    0.00  100.00    16  |__pigz
14时05分27秒  1010         -    219301  100.00    0.00    0.00  100.00    15  |__pigz
14时05分27秒  1010         -    219302  100.00    1.00    0.00  100.00    24  |__pigz
```

`pidstat  -p $(pgrep pigz)  1` outputs as below:

```
14时07分59秒   UID       PID    %usr %system  %guest    %CPU   CPU  Command
14时08分00秒  1010    219296  100.00   15.00    0.00  100.00    25  pigz
14时08分01秒  1010    219296  100.00   16.00    0.00  100.00    17  pigz
14时08分02秒  1010    219296  100.00   16.00    0.00  100.00     0  pigz
```

**It seems that `%usr/%system/%CPU` is a sum of all threads, but with a limitation 100. Why setting up such limitation? Is it a bug or by design?**

use option `-I`, `pidstat -I -p $(pgrep pigz)  1` outputs as below:

* My machine has 104cores, so `431/104 ≈ 4%`, so the reported value of `%CPU` is correct.
* But `%usr` is still 100%, which is not affected by `-I`

```
14时13分33秒   UID       PID    %usr %system  %guest    %CPU   CPU  Command
14时13分34秒  1010    219296  100.00   17.00    0.00    4.29     6  pigz
14时13分35秒  1010    219296  100.00   22.00    0.00    4.34    27  pigz
14时13分36秒  1010    219296  100.00   23.00    0.00    4.36    56  pigz
14时13分37秒  1010    219296  100.00   14.00    0.00    4.28    56  pigz
```

**Why only `%CPU` take SMP into consideration while `%usr %system  %guest` not when specifying the option `-I`**

**Comment by brofu** [comment]
According to the code,

`

      /* g_itv is multiplied by the number of processors */
      g_itv = get_interval(uptime[prev], uptime[curr]);

      if (cpu_nr > 1) {
          /* SMP machines */
          itv = get_interval(uptime0[prev], uptime0[curr]);
      }
      else {
          /* UP machines */
          itv = g_itv;
      }

      if (DISPLAY_ONELINE(pidflag)) {
          if (DISPLAY_TASK_STATS(tskflag)) {
              again += write_pid_task_all_stats(prev, curr, dis,
                          ¦   ¦itv, g_itv);
          }
          if (DISPLAY_CHILD_STATS(tskflag)) {
              again += write_pid_child_all_stats(prev, curr, dis, itv);
          }
      }
      else {
          /* Display CPU stats */
          if (DISPLAY_CPU(actflag)) {

              if (DISPLAY_TASK_STATS(tskflag)) {
                  again += write_pid_task_cpu_stats(prev, curr, dis, disp_avg,
                                  ¦ prev_string, curr_string,
                                  ¦ itv, g_itv);
              }
              if (DISPLAY_CHILD_STATS(tskflag)) {
                  again += write_pid_child_cpu_stats(prev, curr, dis, disp_avg,
                                  ¦  prev_string, curr_string);
              }
          }

`

The reason for this issue, is that, var `itv` is calculated only by the uptime of CPU0 (when cpu number > 1), but actually, the process is being running with multiple CPU, hence, the value may > 100%

And with `-I` parameter, the value of `%CPU` in the result is divided by CPU number. and, it should fits the equation

`

%CPU * cpu_number = %usr + %system

`

But not sure this behaviour is as designed, or a bug.

**Comment by gns333** [comment]
I had the same problem, but I found that from 11.7.3 this problem has been fixed

**Comment by liuyehcf** [comment]
This problem has been fixed in the latest version.
