### ISSUE TITLE
Usage says that timestamps are optional

### ISSUE THREAD

**Issue by rillig** [sysstat/sysstat#350]
The usage message says:
> [ -s [ <start_time> ] ] [ -e [ <end_time> ] ]

This means that it is possible to specify the option `-s` but omit the timestamp.
[The code](https://github.com/sysstat/sysstat/blob/8ee340bfd1a65ef0ede0a3138f0422cbbc495f71/sar.c#L1417) contradicts this.

**Comment by rillig** [comment]
While here, the usage messages differ, probably unintendedly. One says `time_start`, the other `start_time`. Same for `time_end` and `end_time`. There, the timestamp is also marked as optional, when in fact it probably isn't.

**Comment by sysstat** [comment]
`start_time` and `end_time` are actually optional. With no time passed as argument, the default starting time and ending time are used (08:00:00 and 18:00:00 respectively).

And yes, I forgot to replace a `time_start`  and a `time_end` with  `start_time` and `end_time`. This is fixed now.

**Comment by rillig** [comment]
Ah, thanks, upon reading the code of `parse_timestamp`, each timestamp is indeed optional, so I re-added the brackets to the German translation. Thanks for the explanation.

**Comment by rillig** [comment]
Reading `parse_timestamp` again, the heuristics look very brittle to me. Do you have automatic tests for command lines like `-s --fs=something`, to ensure that the second option is never interpreted as a timestamp? As far as I've read the code, `parse_timestamp` doesn't check that the colons are there and that the other characters are digits. And `atoi` happily returns 0 for nonnumeric arguments.

**Comment by sysstat** [comment]
You are perfectly right. It's now relatively easy to fool `sar` and `sadf` and make them interpret the argument following `-s` or `-e` as a timestamp even when it's not. At least it should check that this argument doesn't start with a dash.
I will update the code to fix this.
