### ISSUE TITLE
Please GPG sign your release tags

### ISSUE THREAD

**Issue by vt-alt** [sysstat/sysstat#351]
Would be good if you also sign your release tags with GPG,

This is easy to do, just generate a GPG key, and then, when new tag needs to be created, add `-s` option to `git tag -a`.

This will be useful security addition (against supply chain attacks)) for people building `sysstat` from git (such as Linux distributions).

If you agree, also please publish the key under https://github.com/sysstat.gpg

Thanks,

**Comment by sysstat** [comment]
Thanks for this piece of advice.
I will do it next time.

**Comment by vt-alt** [comment]
Great, thanks!
