### ISSUE TITLE
Idea: Add full CPU pressure stats

### ISSUE THREAD

**Issue by MrPippin66** [sysstat/sysstat#352]
Under the new PSI counters, the CPU counters only includes the "some" parameters.

Not sure if there was a reason the "full" counters weren't included, but I'd like to request they be added.

**Comment by sysstat** [comment]
It seems that the "full" counters for CPU are not reported.
From the kernel 6.1.10 documentation (Documentation/accounting/psi.rst) :
```
CPU full is undefined at the system level, but has been reported
since 5.13, so it is set to zero for backward compatibility.
```

**Comment by MrPippin66** [comment]
Interesting. I'd never noticed that.
