### ISSUE TITLE
The readings of the iostat commands w/s, wkb/s, and %util are overflowed.

### ISSUE THREAD

**Issue by wenpei-z** [sysstat/sysstat#355]
When a container is created, the DM device is quickly creates and deletes. An error occurred when using the iostats command to determine if the device is newly created. The calculation result may generate a negative value, causing overflow.
![image](https://user-images.githubusercontent.com/107899637/231677679-d6c49eb5-0a5f-461c-bb7e-d29a4e2c1451.png)

Reproduction Procedure
1.Create /dev/sdc.
dmsetup create test --table "0 20971520 linear /dev/sdc 0"

2.Run the iostat command in the background.
iostat -t -x 1 >test.log &

3.Add DM devices, deliver I/Os, and delete DM devices.
for i in {1..1000} ;do dmsetup create test --table "0 20971520 linear /dev/sdc 0";dd if=/dev/zero of=/dev/dm-3 bs=1M count=1 oflag=direct;sleep 0.3; dmsetup remove test ;done

4.Viewing Logs
grep 184467 test.log
![image](https://user-images.githubusercontent.com/107899637/231677796-f38e24f3-40ab-4bfc-b52b-91d14b687273.png)
![image](https://user-images.githubusercontent.com/107899637/231677895-a333edbc-6b75-4898-854b-ff39edca914e.png)

**Comment by sysstat** [comment]
Thank you for this bug report.
Commit c43167c tries to fix the problem. Tell me if things are OK for you now.
Yet I consider this fix as only partially satisfactory as it will only check for possible negative values and display 0.0 (instead of a large number) if the counter has decreased.

**Comment by wenpei-z** [comment]
I'm glad to receive your reply. Although this patch can solve the issues in w/s, wkb/s, and %util, other fields may also overflow.I used the original steps to reproduce and still have overflow data
![image](https://github.com/sysstat/sysstat/assets/107899637/5e5dad47-d25a-4415-aba2-aeca0fd9fce5)

**Comment by wenpei-z** [comment]
Now there is no abnormal data in my environment, thanks

**Comment by wenpei-z** [comment]
One last question, do the fields rd_ticks, wr_ticks, and dc_ticks also need to undergo this kind of judgment?

**Comment by zhang-paanan** [comment]
I’d like to know the result of the above comments @sysstat
