### ISSUE TITLE
Tag releases please

### ISSUE THREAD

**Issue by vt-alt** [sysstat/sysstat#363]
Can you also tag releases, so they are more noticeable for people monitoring git.

Currently `sysstat-12.7.4` is not tagged (and does not appear on [Download](http://sebastien.godard.pagesperso-orange.fr/download.html) page) while it is in [CHANGES](https://github.com/sysstat/sysstat/blob/master/CHANGES) and mentioned in commit history.

**Comment by sysstat** [comment]
Oopss... I actually forgot to upload tags to GitHub. This is now done. Thanks.

Wrt the Download page, my Internet provider will stop hosting personal web sites before the end of this year. So I will no longer update `sebastien.godard.pagesperso-orange.fr` (including its Download page of course). I have to find another solution, maybe using `sysstat.github.io`

**Comment by natoscott** [comment]
If they allow you to set a DNS CNAME (most ISPs do) you can keep the same URL using github pages:
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by sysstat** [comment]
> If they allow you to set a DNS CNAME (most ISPs do) you can keep the same URL using github pages: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

Thanks for the hint.
I will definitely do it if I can do it for free...
