### ISSUE TITLE
systemd timer doesn't collect 00:00:00 data 

### ISSUE THREAD

**Issue by martinvonwittich** [sysstat/sysstat#366]
I'm currently trying to investigate an issue where I suspect the load on a server to peak at 00:00:00. Unfortunately, when using the systemd service and timer provided by sysstat, no data at 00:00:00 is collected - the data from the previous day ends at 23:50, and the data from the next day begins at 0:10:

```
host ~ # LC_ALL=C sar -q -f /var/log/sysstat/sa20230702 | tail -n 2
23:50:06            7      1651      0.06      0.03      0.00         0
Average:            0      1573      0.08      0.08      0.05         0
```

```
host ~ # LC_ALL=C sar -q | head -n 4
Linux 5.10.0-15-amd64 (host)        07/03/23        _x86_64_        (32 CPU)

00:00:01      runq-sz  plist-sz   ldavg-1   ldavg-5  ldavg-15   blocked
00:10:08            0      1573      0.03      0.05      0.01         0
```

I assume the problem is the one that is documented here: http://sebastien.godard.pagesperso-orange.fr/faq.html#sar-2.12

>  Sysstat does get its data at midnight, but two data samples are needed to display the values. 
> [...]
> Things are much easier with recent sysstat versions (12.5.1 and later): You simply have to run sa1 with its option `--rotate` shortly after midnight to add a statistics record to the system activity daily data file of the previous day.

Should there be a separate service and timer that calls `sa1 --rotate`?

**Comment by sysstat** [comment]
Hi,
You're right. I also think that another service and timer should call `sa1 --rotate` on midnight.
I will add them to sysstat.

**Comment by sysstat** [comment]
Commit 7d317ec adds the expected feature.
