### ISSUE TITLE
Does not ./configure with error: configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by FlashT** [sysstat/sysstat#37]
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/flasht/sysstat-master':
configure: error: C compiler cannot create executables

gcc is installed... i do use it and I assure you that it can create executables... so what is the problem?

----------------------------------------------------------------------------------------------------------------------

## ----------- ##

configure:2316: checking for gcc
configure:2332: found /usr/bin/gcc
configure:2343: result: gcc
configure:2572: checking for C compiler version
configure:2581: gcc --version >&5
gcc-4.4.real (Debian 4.4.5-8) 4.4.5
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2592: $? = 0
configure:2581: gcc -v >&5
Using built-in specs.
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.4.5-8' --with-bugurl=file:///usr/share/doc/gcc-4.4/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.4 --enable-shared --enable-multiarch --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.4 --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-objc-gc --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.4.5 (Debian 4.4.5-8) 
configure:2592: $? = 0
configure:2581: gcc -V >&5
gcc-4.4.real: '-V' option must have argument
configure:2592: $? = 1
configure:2581: gcc -qversion >&5
gcc-4.4.real: unrecognized option '-qversion'
gcc-4.4.real: no input files
configure:2592: $? = 1
configure:2612: checking whether the C compiler works
configure:2634: gcc    conftest.c  >&5
/usr/bin/ld.bfd.real: cannot find -lgcc_s
collect2: ld returned 1 exit status
configure:2638: $? = 1
configure:2676: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "sysstat"
| #define PACKAGE_TARNAME "sysstat"
| #define PACKAGE_VERSION "11.1.3"
| #define PACKAGE_STRING "sysstat 11.1.3"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:2681: error: in `/home/flasht/sysstat-master':
configure:2683: error: C compiler cannot create executables
See `config.log' for more details

**Comment by FlashT** [comment]
PS. It is `gcc -v` not `gcc -V` ...

**Comment by FlashT** [comment]
The problem is probably because ia32-lib is missing, but it is not 32 bit system!!! So this is a bug.

**Comment by sysstat** [comment]
Not a sysstat bug.

**Comment by FlashT** [comment]
In fact it is. I was able to complile it by fixing config file. Still mstat
seems to have bug:


11:31:05 PM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal
 %guest   %idle

11:31:06 PM  all    5.07    0.00    9.85    0.00    0.00    0.00    0.00
 0.00   85.07

11:31:06 PM    0    0.00    0.00    0.00    0.00    0.00    0.00    0.00
 0.00  100.00

11:31:06 PM    1   34.00    0.00   66.00    0.00    0.00    0.00    0.00
 0.00    0.00

11:31:06 PM    2    0.00    0.00    0.00    0.00    0.00    0.00    0.00
 0.00  100.00

11:31:06 PM    3    0.00    0.00    0.00    0.00    0.00    0.00    0.00
 0.00  100.00

11:31:06 PM    4    0.00    0.00    0.00    0.00    0.00    0.00    0.00
 0.00    0.00

11:31:06 PM    5    0.00    0.00    0.00    0.00    0.00    0.00    0.00
 0.00  100.00

11:31:06 PM    6    0.00    0.00    0.00    0.00    0.00    0.00    0.00
 0.00  100.00

11:31:06 PM    7    0.00    0.00    0.00    0.00    0.00    0.00    0.00
 0.00  100.00


Look at CPU 4 -> 0% idle and 0% overall usage... lies! :D


21 sty 2015 17:49 "GODARD Sebastien" <notifications@github.com> napisał(a):
