### ISSUE TITLE
Feature Request: add all cores metrics to `sar -u`

### ISSUE THREAD

**Issue by carlosrodfern** [sysstat/sysstat#371]
It would be great to have all cores metrics in `sar -u`, and especially in the archives for later inspection.

**Comment by stevekay** [comment]
Would existing functionality, using `sar -u -P ALL`, cover this requirement ?

**Comment by carlosrodfern** [comment]
Absolutely. I didn't catch the `-P` option was available for `-u` even after being in `man sar` a 100 times.
