### ISSUE TITLE
Provide release tarballs via github

### ISSUE THREAD

**Issue by kanavin** [sysstat/sysstat#372]
Now that the original homepage is going away, it would be good to start providing release tarballs here:
https://github.com/sysstat/sysstat/releases

(perhaps historical tarballs aren't needed, just the two latest development/stable releases, and all new releases going forward).

In a related note, on that page it should be clear that 12.6.x is stable, and 12.7.x is development (and so forth in the future).

Before anyone says, github archives made automatically by github from tags are not release tarballs. They're also unstable and so make source integrity checks impossible.

**Comment by kanavin** [comment]
Okay, I didn't yet see https://sysstat.github.io/ when I wrote this. The new homepage is somewhat problematic as we (Yocto project) and some other distributions use automatic tooling to discover and update distro packaging to latest versions. 

The tooling expects this:
- there is a stable webpage (static URI) that links to the latest tarball. https://sysstat.github.io/versions.html doesn't link to the latest, but it can be easily fixed.
- the tarballs don't move around; once a version is published at a certain URI it stays there. What I see is that once a tarball is no longer the latest, it's moved to systat-packages/previous/ - please don't do this.

If you can do these, I'd appreciate!

**Comment by sysstat** [comment]
OK, I updated https://sysstat.github.io.
"Previous versions" page has been renamed to "Download" and now also includes the latest sysstat tarball (tar.xz format).
This should meet your needs.

**Comment by kanavin** [comment]
Thanks, this is perfect!

**Comment by kanavin** [comment]
The homepage link should be updated here as it still points to the old page:

https://github.com/sysstat/sysstat

**Comment by sysstat** [comment]
> The homepage link should be updated here as it still points to the old page:
> 
> https://github.com/sysstat/sysstat

This is now fixed.
Thanks
