### ISSUE TITLE
Is 12.7.x development or new stable? Is odd-even version scheme still in place?

### ISSUE THREAD

**Issue by kanavin** [sysstat/sysstat#373]
The old homepage does say that 12.7.x is a development serie, and stable 12.6.x is stable one, but the new home page does not. So has the policy changed? Which version should be taken for distribution packaging?

**Comment by sysstat** [comment]
I confirm that odd and even version numbers no longer reflect development or stable versions for sysstat.
The fixes added to the stable branch were often minimal, and the extensive non regression tests I use with sysstat make it unlikely to get a serious bug from a new version affecting previously existing functions (well I hope so :-) )
So 12.7.x should now be used for distribution packaging, and a move to 12.8.x will only be based on a personal decision and unrelated to the start of a stable branch.

**Comment by sysstat** [comment]
@kraptor You're right. I updated README and FAQ files accordingly (see commit ff0e3a5).
