### ISSUE TITLE
[RFE] `sar` should have unique column names

### ISSUE THREAD

**Issue by lzaoral** [sysstat/sysstat#383]
One of our customers raised the following RFE.  Since I don't want to deliberately change the output format of `sar` in existing major releases of RHEL, I'd like the upstream to consider this suggestion and if accepted, I'll make sure that it will be present in RHEL 10:

> `sar` output results can be used in many different ways, but should have unique names because the same names can be confusing.

For example the `retrans/s` column:
```bash
$ sar -n ETCP 1 2
:
08:38:08 AM atmptf/s estres/s retrans/s isegerr/s orsts/s
08:38:09 AM 0.00 0.00 0.00 0.00 0.00
08:38:10 AM 0.00 0.00 0.00 0.00 0.00
Average: 0.00 0.00 0.00 0.00 0.00

$ sar -n NFS 1 2
:
08:38:25 AM call/s retrans/s read/s write/s access/s getatt/s
08:38:26 AM 0.00 0.00 0.00 0.00 0.00 0.00
08:38:27 AM 0.00 0.00 0.00 0.00 0.00 0.00
Average: 0.00 0.00 0.00 0.00 0.00 0.00
```

**Comment by sysstat** [comment]
I agree. One of the `retrans/s` field names should be changed in the output from both `sar` and `sadf`.
But such a change will probably break some third party tools which parse `sar` (or `sadf`) output and I'm wondering if this is acceptable... Any opinion about this?

**Comment by lzaoral** [comment]
I don't have a strong opinion about this.  One one hand, field renaming is not a common practise for this project, on the other hand, this field duplicity can be confusing when you execute, e.g. `sar -n ALL 1 1`.

**Comment by lzaoral** [comment]
Thank you for implementing this RFE, Sebastien!
