### ISSUE TITLE
Why there is no 12.6.2 source at https://sysstat.github.io/versions.html?

### ISSUE THREAD

**Issue by Mingli-Yu** [sysstat/sysstat#385]
For some reason, I'm tracking the 12.6.2 version. But why there is no 12.6.2 source at https://sysstat.github.io/versions.html? Thanks!

**Comment by sysstat** [comment]
You're right. I should probably replace 12.6.1 version with 12.6.2 in the list.
Meanwhile you can find 12.6.2 [here](https://github.com/sysstat/sysstat/tags)

**Comment by sysstat** [comment]
OK, in fact I have just added 12.6.2 to the list in the [Download](https://sysstat.github.io/versions.html) page.

**Comment by Mingli-Yu** [comment]
Thanks @sysstat  for your update!

**Comment by Mingli-Yu** [comment]
Just noticed I have downloaded http://pagesperso-orange.fr/sebastien.godard/sysstat-12.6.2.tar.xz previously and saved one copy locally and its sha1sum is a91877220a64dbc095fbcbb3c1c7d2e20f30f45e.
But after I download from https://sysstat.github.io/sysstat-packages/sysstat-12.6.2.tar.xz just now, the sha1sum turns to be d3adbfd91c15de6c0ae1a639f088a6c446f67bb3, not sure why they are different though they both are 12.6.2 release source.

**Comment by sysstat** [comment]
Don't worry about this new sha1sum. I didn't have the `tar.xz` package at hand so I had to make it again.

**Comment by Mingli-Yu** [comment]
Many thanks @sysstat  for your confirmation!
