### ISSUE TITLE
[Question] Why can't iostat provide data io for directories?

### ISSUE THREAD

**Issue by gitthnx** [sysstat/sysstat#393]
Why is there no option for iostat for monitoring directory io? (thx)

**Comment by sysstat** [comment]
`iostat` reports statistics for devices and partitions only, not files.
And I'm not sure that IO statistics for directories can be easily retrieved anyway.

**Comment by gitthnx** [comment]
> `iostat` reports statistics for devices and partitions only, not files.  

Iostat is very helpful for me with everyday usage for oversight on mainly write access to partitions. Thanks for Your work and support on that system tool.

>And I'm not sure that IO statistics for directories can be easily retrieved anyway.

This is what i'm trying to understand and to learn more about.
Please, can You explain in more detail, why this is more difficult than getting io measuring data for partitions? 
Do You know of any tool summarizing data for a filesystem's directory, providing input/output data rate or absolute data for a period of time? 
Are common methods for retrieving io data dependent on the filesystem type? 

If there are (timely) throughput or storage size limitations obviously one wants to know what files and processes are causing that, if recognized within iostat output. There are tools available for that like iotop, sar or inotify* utils. It looks like an useful addition to me, if there's information about what directory is burdened with high(er than usual) data io, also.  
Additionally useful with benchmarking tools (known or startup sources) for storage devices and on OS upgrades (including new self-compiled Kernels). 

Thanks for Your response and time.
