### ISSUE TITLE
[RFE] Collect HBA statistics

### ISSUE THREAD

**Issue by stevekay** [sysstat/sysstat#44]
Wondered about the possibility of collecting FC HBA statistics (/sys/class/fc_host/statistics).  Tend to see a few real-world performance issues at the SAN fabric level so may be useful.

Have started with some early ideas at https://github.com/stevekay/sysstat, introducing a "-a" parameter and just collecting txframes and rxframes currently.

**Comment by jaunix** [comment]
Improved and submitted new pull request https://github.com/sysstat/sysstat/pull/64

**Comment by stevekay** [comment]
Now merged, thanks, so closing.
