### ISSUE TITLE
sadf: New output format to add : SVG ?

### ISSUE THREAD

**Issue by sebpcspkr** [sysstat/sysstat#51]
Hello,
I appreciate a lot sysstat, and I recently made a try to convert sadf data into svg (sar2svg).
I think that should be a great enhancement if sadf has the option internally (-S ?),  so I suggest you to take this into account :)
Bye

**Comment by jaunix** [comment]
Link to your repo hosting this -> https://github.com/sebpcspkr/sar2svg

**Comment by sysstat** [comment]
This feature seems interesting. I will have a look at sar2svg and get back in touch with you.

**Comment by sysstat** [comment]
Sorry, couldn't make it work. Please give more details on how to use it.

**Comment by sebpcspkr** [comment]
Here how to do this with Debian 8 :
# apt-get install nodejs
Retrieve the sar2svg.js file
# nodejs sar2svg.js &
Open your browser into http://<theHost>:1337/

Maybe it doesn't fit in over OS than Debian 8 
Could you please send me the error ?

**Comment by sysstat** [comment]
Thanks, but you should **really** put these notes in your README file for the guys like me who never use these tools. OK, so for my part:

yum install nodejs
node sar21svg.js &

(my nodejs package contains the node binary).
And opening my browser with http://127.0.0.1:1337 now gives the graphs (it's cool, but a pity that the caption is written right in the middle of the graphs).
Now how would you consider integrating this output as a new format for sadf?

**Comment by sebpcspkr** [comment]
You're right : I'll update the README.
About the caption, I'm not sure having the same : there's the header with host, then the first graph then its caption, then the second graph,... vertically. 

Now talking about the new ouput format for sadf, sadf has already multiple export file format (-d, -j, -p), so another potential export format seems to me to be the svg file format. The sar2ssvg.js has 2 functions : it transforms sadf -d into svg, and it is accessble from browser with nodejs. If sysstat add this ability, sar2svg will only have the secund function and the svg file will be better done I think.

When you have to look into sysstat data, the first look is often to globally look at graphs, so you have to export you sadf data, then import it into another one tools to view something.
If sadf is capable of exporting into svg, you take the svg into your browser (even without sar2svg nor nodejs).

That was the initial idea...

Then, thank you for the feedback.

**Comment by sysstat** [comment]
I'm still convinced that this would make a really nice, new feature for sadf. Do you feel ready to add it yourself? Else I could try to do it but:
* Unfortunately I have very little time to work on sysstat nowadays
* I don't know the SVG format nor the Java language (I have never made some code with it). So you would have to explain every detail in order for me to be able to add the feature...

**Comment by sebpcspkr** [comment]
I'll take a look into the sysstat's code to see if I can handle it ...but I can't tell when (very little time to work on sysstat too)
The SVG file format is quite simple (based on XML), the way I used for sar2svg too - you can view this into source file from browser (nota bene about the language : it's not Java but Javascript, it's nearer from C).
So I think we should say : the first who do it tell it to the other one :)
...
And if antoher one decide do to it before, we should say this one is welcome!
:)

**Comment by sebpcspkr** [comment]
NB : You were right about the caption of sar2svg/ I just changed it/ Thanks.

**Comment by sysstat** [comment]
Hi,
Just FYI: I've started to work on the addition of SVG output format to sadf. Hope to make a first release with very limited possibilities in the coming weeks.

**Comment by sebpcspkr** [comment]
Hi, thanks for the FYI . I'll test this first release :)

**Comment by sebpcspkr** [comment]
I'm late but that's great!
Just tried the master on debian jessie to take a look (sadf -g /var/log/sysstat/sa29  -- -A >/tmp/a.svg into iceweaseal)  :+1:
