### ISSUE TITLE
[RFE] sadf outputing multi-day periods

### ISSUE THREAD

**Issue by jimis** [sysstat/sysstat#57]
Hi Sebastien,

I'm trying to change `sargraph` (in contrib) to generate plots of arbitrary time periods. Under the hood, of course it uses `sadf` to fetch the data from the `sa` files. 

I really like how you can pass arbitrary start and end time to sadf together with interval and it will give you the proper number of datapoints, that are not only the values at the specific times, but they are **averaged** over the time period (right?). E.g. to get hourly averages of CPU activity:

```sadf -d -s 09:00:00 -e 12:00:00  --  -u 3600 /var/log/sa/sa26```

What would be awesome is if sadf could combine many different files, compressed or not, to extract and average the data between arbitrary dates. Example usage:

```sadf -d --sa-path=/var/log/sa  -s 20150301:0000 -e 20150331:2359  --  3600```

What do you think? Would such a feature be easy to implement?

**Comment by sysstat** [comment]
Most values displayed by sar are actually averaged over the time period.
Wrt the second point, I don't think that this is sadf's purpose to combine multiple files. We should be careful about such "features" that may end up bogging down sysstat's code for limited usefulness. As you can notice, I'm not really excited about it... :confused:

**Comment by jimis** [comment]
OK feel free to close this issue then, I'll try to implement the functionality in the script that calls `sadf`. It's a pity though because I'll probably have to duplicate the averaging logic. Because of this IMHO it would fit very well in `sadf`, but of course I wouldn't be thrilled either to incorporate a bunch of libraries and logic to decompress the proper files.

**Comment by smaudet** [comment]
It seems like this would be functionality you would want... I have data over a past month, it seems exceedingly tedious to go through 28+ days of data and manually check graphs when all I wanted to do was look for spikes in the last month...

Maybe there is a better tool than sysstat for this, and I should uninstall this program? It generates messages in my log file, and I don't use it otherwise.

**Comment by natoscott** [comment]
@smaudet you might be able to use the support in sysstat for generating Performance Co-Pilot (pcp.io) archives?  Refer to the -l and -O options to sadf(1) for this functionality.

These archives can then be joined using the PCP pmlogextract(1) tool and there are other tools provided in PCP that allow searching for spikes - pmchart(1), pmie(1), pmlogsummary(1) and pmdiff(1) for example.
