### ISSUE TITLE
Sysstat mail report script

### ISSUE THREAD

**Issue by desbma** [sysstat/sysstat#67]
Hello,

First, I use your great software Sysstat for a long time, thank you for writing it and making it open source.

I have written a script to automatically generate and send an email report every day/week/month with graphs generated from sysstat data.

I just put the code on GitHub today: https://github.com/desbma/sysstat_mail_report 

If you could mention it in the FAQ of your website (http://sebastien.godard.pagesperso-orange.fr/faq.html, item 2.11) that would be nice. :)

Thanks

**Comment by sysstat** [comment]
Yep, this will be done with the release of next sysstat release (the FAQ included in sysstat source package will also be updated).

**Comment by desbma** [comment]
Thanks
