### ISSUE TITLE
Max value for txkB/s in sar

### ISSUE THREAD

**Issue by renaudhager** [sysstat/sysstat#72]
Hello guys,

I have a pretty strange behaviour with sar, we generate HTTP traffic on a 10G nic, we graph the throughput on grafana and we see value  like ~8/9 Gb/s on this nic.

But sar seems to be stuck at  this value :1 200 000 txkB/s.

Do you have any ideas about this max value ?

We have the same behaviour with nmon, but with iftop we can see the real throughput.

OS : centos 7 x86_64

**Comment by sysstat** [comment]
Well, this is probably because sar writes the value in kB/s (read: kilobytes per second) whereas iftop maybe displays the value in kb/s (read: kilobits per second)...?

**Comment by renaudhager** [comment]
yes ...

Sorry for that I read too fast :-( 

Thx !
