### ISSUE TITLE
[RFE] add sa2 option to avoid sarDD report generation

### ISSUE THREAD

**Issue by abone28** [sysstat/sysstat#81]
sa2 script generates text reports SA_DIR/sarDD, but I'm fine with on demand reports generation, so prepared text reports in SA_DIR are just wasting disk space.

Currently there is no possibility to disable report generation without modifying sa2 script. Can you consider implementing something like option MAKE_REPORT=false in SYSCONFIG_DIR/sysstat that disables text report generation in SA_DIR?

**Comment by stevekay** [comment]
If you set HISTORY to 1, rather than the default of 7, you'll reduce disk usage.

Alternatively, perhaps the script should be revised to skip report generation altogether if HISTORY is set to zero ?

**Comment by abone28** [comment]
No. I do need saDD files, so setting HISTORY=1 is not an option. What I don't need is predefined text reports sarDD generated on line 46 in file sa2.in. I may generate historical reports with sar -f or sadc. Currently there is no possibility to disable them, but they are useless for me because a can do sar -f SA_DIR/saDD manually when I need to see report.

**Comment by portante** [comment]
@abone28, I believe there are `.txt` and `.xml` reports generated currently, so perhaps a setting like, `REPORTS="txt,xml"`, where if you set it to `""` nothing would be generated, `"txt"` would just generate `.txt` reports?

**Comment by abone28** [comment]
@portante I would agree to any variant that allow me to turn reports on and off.

**Comment by sysstat** [comment]
At the present time sa2 script only generates text reports (the so-called sarDD files).
I agree to add a variable in sysstat configuration file to enable/disable report creation.
This feature will be part of next sysstat release.
