### ISSUE TITLE
11.1.6: make error: tapestat.c: In function 'main'

### ISSUE THREAD

**Issue by AlexIvamoto** [sysstat/sysstat#82]
When compiling from source 11.1.6, make get error:

tapestat.c: In function 'main':
tapestat.c:673: error: invalid application of 'sizeof' to incomplete type 'struct sigaction'
tapestat.c:674: error: invalid use of undefined type 'struct sigaction'
tapestat.c:675: warning: implicit declaration of function 'sigaction'
tapestat.c:675: error: 'SIGALRM' undeclared (first use in this function)
tapestat.c:675: error: (Each undeclared identifier is reported only once
tapestat.c:675: error: for each function it appears in.)
make: *** [tapestat.o] Error 1

**Comment by sysstat** [comment]
Some headers are missing in tapestat.c
Commit 370c5c1 fixes the problem (will be part of next sysstat release).
