### ISSUE TITLE
11.1.6: multiple headers in sar output CPU section

### ISSUE THREAD

**Issue by AlexIvamoto** [sysstat/sysstat#84]
11.1.6 In report files /var/log/sa/sarDD  multiple headers in CPU section:

 CPU      %usr     %nice      %sys   %iowait    %steal      %irq     %soft    %guest    %gnice     %idle 
bla-bla-bla
 CPU      %usr     %nice      %sys   %iowait    %steal      %irq     %soft    %guest    %gnice     %idle 
...
 CPU      %usr     %nice      %sys   %iowait    %steal      %irq     %soft    %guest    %gnice     %idle 

For example in version 7.0.2 only one header in CPU section.

**Comment by sysstat** [comment]
This is was is expected from sar. IOW it's a feature :-)
Sar has been modified to periodically print the headers so that the user can easily know the meaning of the various fields, especially for long listings.
