### ISSUE TITLE
Network monitoring

### ISSUE THREAD

**Issue by sebek72** [sysstat/sysstat#85]
Hi using sysstat-9.0.4-27.el6.i686 on centos 6.6 the network stats are wrong.

I´m doing an rsync of large files an see heavy network traffic with iftop but not with sar
(rxKB/s and txKB/s are  0.00):

sar -n DEV 2 1
Linux 2.6.32-504.16.2.el6.i686 (XXXhost) 	10/28/2015 	_i686_	(12 CPU)

01:15:25 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s
01:15:27 PM        lo   1192.78   1192.78      0.00      0.00      0.00      0.00      0.00
01:15:27 PM       em1  14211.86  69996.91      0.00      0.00      0.00      0.00    176.80
01:15:27 PM       em2      5.67      5.67      0.43      0.43      0.00      0.00      0.00
01:15:27 PM       em3      0.00      0.00      0.00      0.00      0.00      0.00      0.00
01:15:27 PM       em4      0.00      0.00      0.00      0.00      0.00      0.00      0.00
01:15:27 PM      em49      2.58      0.00      0.00      0.00      0.00      0.00      2.58
01:15:27 PM      em50      0.00      0.00      0.00      0.00      0.00      0.00      0.00
01:15:27 PM      em51      0.00      0.00      0.00      0.00      0.00      0.00      0.00
01:15:27 PM      em52      0.00      0.00      0.00      0.00      0.00      0.00      0.00
01:15:27 PM     bond0  14214.43  69996.91      0.00      0.00      0.00      0.00    179.38
01:15:27 PM     bond1      0.00      0.00      0.00      0.00      0.00      0.00      0.00

Average:        IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s
Average:           lo   1192.78   1192.78      0.00      0.00      0.00      0.00      0.00
Average:          em1  14211.86  69996.91      0.00      0.00      0.00      0.00    176.80
Average:          em2      5.67      5.67      0.43      0.43      0.00      0.00      0.00
Average:          em3      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:          em4      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:         em49      2.58      0.00      0.00      0.00      0.00      0.00      2.58
Average:         em50      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:         em51      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:         em52      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:        bond0  14214.43  69996.91      0.00      0.00      0.00      0.00    179.38
Average:        bond1      0.00      0.00      0.00      0.00      0.00      0.00      0.00

iftop:

TX:             cum:   1.32GB   peak:    758Mb                                                                                                                                                               rates:    716Mb   679Mb   676Mb
RX:                    14.1MB           7.74Mb                                                                                                                                                                        7.17Mb  7.15Mb  7.06Mb
TOTAL:                 1.33GB            765Mb                                                                                                                                                                         723Mb   686Mb   683Mb

**Comment by portante** [comment]
I could be wrong, but I think that might be a bug in CentOS 6.6.  Check out 6.7.

**Comment by sebek72** [comment]
I cannot update to 6.7 .The bug should be where? Can I update a specific package to avoid it?

**Comment by portante** [comment]
It's a kernel bug with whatever sar -n DEV reads.  The counters are not properly updated.  I don't have a Bugzilla ID for this.  We saw it with RHEL 6.6 and upgraded to RHEL 6.7 to get the fix.

**Comment by sysstat** [comment]
Peter's explanation may be the right one because I don't see any good reasons(*) for sar to display zero values for network traffic, except if the kernel's counters are not properly updated.

_(*)Well... this is not totally true in fact. I saw exactly the same problem a few years ago when a 32-bit version of sar was used on an x86_64 machine. The solution was then to use the proper version of sar for the target architecture (or to recompile it on the target machine). But this is not your problem here._

**Comment by sebek72** [comment]
Thank you. Will look into it.

**Comment by sebek72** [comment]
I have found the bug report but it is specific to ixgbe driver:
https://bugs.centos.org/view.php?id=7807

In my case the counters (sar output) work after server reboot, but after a while it stops to work.

**Comment by sysstat** [comment]
Network data are read from /proc/net/dev file.

**Comment by sebek72** [comment]
Hi
I've tried with the newest 6.7 kernel. Same issue as before. After server reboot it works for a minute.


Average:        bond0  74965.99  15994.92 105963.01   1182.28      0.00      0.00    245.18
Average:        bond0  69438.19  15563.32  98610.59   1128.75      0.00      0.00    224.12

after a while:

Average:        bond0  80083.59  16224.62      0.00   1170.42      0.00      0.00    233.33
Average:        bond0  78564.00  16431.50      0.00   1185.33      0.00      0.00    224.00

**Comment by sysstat** [comment]
Can you send me a sar binary data file so that I can have a look at the data? (If collection is not enabled, create the file with eg. "sar -o datafile 2 10" and make sure that there is some network traffic meanwhile).
Also send me the contents of your /proc/net/dev file.
Thanks.

**Comment by sebek72** [comment]
cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo: 71393238595 207633902    0    0    0     0          0         0 71393238595 207633902    0    0    0     0       0          0
   em1: 12843434955 85986278    0    0    0     0          0   1557842 72533380224 158558921    0    0    0     0       0          0
 bond0: 12843434955 85986278    0    0    0     0          0   1557842 72533380224 158558921    0    0    0     0       0          0

**Comment by sysstat** [comment]
Could you try sysstat version 10.1.3 or later?
Looking at your /proc/net/dev file shows that the number of bytes (received and transmitted) are greater than ULONG_MAX.
From sysstat changelog, version 10.1.3 (released at the end of 2012) includes a patch that changed network counters (used by sar -n {DEV | EDEV }) to unsigned long long to keep in sync with current kernels and to be able to handle values greater than ULONG_MAX.

**Comment by sebek72** [comment]
It works with 10.1.8 (latest). Thank you

Average:        bond0  63285.50  14171.00  89670.75   1021.29      0.00      0.00    235.50     73.46

**Comment by sebek72** [comment]
I just realized the cron is not enabled by default.
I tried to build with --enable-install-cron but the cron.d/sysstat has everything commented out.
Am I doing something wrong?

**Comment by sysstat** [comment]
No, that's OK. Crontab entries (or some units if you use systemd) are installed when you enter "make install" as root providing that you built sysstat with --enable-install-cron.

**Comment by sebek72** [comment]
I am building a new rpm for EL6. The /etc/cron.d/sysstat file is created but all lines are commented out.
