### ISSUE TITLE
v 11.8: sadf file conversion

### ISSUE THREAD

**Issue by venturio1256** [sysstat/sysstat#89]
I upgraded my sysstat package from 10.1.5 to 11.1.8 and I did not find a way to use -c option to convert a saxx binary file created with sadc v 10.1.5 to a readable binary file by sadf 11.1.8

I tried sadf -c /var/log/sa/sa09 > /var/log/sa/sa09_11.8 
Then
sadf -c /var/log/sa/sa09 > /var/log/sa/sa09_11.8 -P ALL /var/log/sa/sa09_11.8

I missed something but I did not figure out
Thanks in advance

**Comment by sysstat** [comment]
The syntax "sadf -c /var/log/sa/sa09 > /var/log/sa/sa09_11.8" is good.
But I also have a problem when I try to convert a file ("Invalid system activity file..."). I will investigate in the coming days and get back in touch with you.

**Comment by venturio1256** [comment]
Hi Sebastien.

Merci!


On Tue, Dec 15, 2015 at 2:47 PM, GODARD Sebastien <notifications@github.com>
wrote:

> The syntax "sadf -c /var/log/sa/sa09 > /var/log/sa/sa09_11.8" is good.
> But I also have a problem when I try to convert a file ("Invalid system
> activity file..."). I will investigate in the coming days and get back in
> touch with you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sysstat/sysstat/issues/89#issuecomment-164906989>.
>



-- 
Christian Thomas
Mobile +1 (720) 746 8575
Landline +1 (720) 381 0054

**Comment by sysstat** [comment]
OK, I found the bug which appeared with version 11.1.5. Additional checks have been added when reading a data file, but  these checks should not display an error message when sadf is used to convert the data file.
Commit 1813967 fixes the problem and will be part of sysstat 11.2.0 to be released this month.
