### ISSUE TITLE
sadf -j outputs malformed json

### ISSUE THREAD

**Issue by grogancolin** [sysstat/sysstat#90]
There is a missing comma between "net-sock" and "fc-hosts".

$ sadf -V                                                                        │
sysstat version 11.1.5                                                                                               
(C) Sebastien Godard (sysstat <at> orange.fr)

Sample output from : $ sadf -j -T -- -A >> sampleSysstat.json

    {
    "sysstat": {
	"sysdata-version": 3.1,
	"hosts": [
		{
			 // snip
			"statistics": [
				{
					"timestamp": { // snip },
					"cpu-load": [ // snip ],
					"process-and-context-switch": {"proc": 0.17, "cswch": 6804.27},
					"swap-pages": {"pswpin": 0.00, "pswpout": 0.00},
					"paging": {"pgpgin": 1.21, "pgpgout": 332.80, "fault": 1541.61, "majflt": 0.01, "pgfree": 2511.99, "pgscank": 0.00, "pgscand": 0.00, "pgsteal": 0.00, "vmeff-percent": 0.00},
					"io": {"tps": 4.92, "io-reads": {"rtps": 0.04, "bread": 2.43}, "io-writes": {"wtps": 4.88, "bwrtn": 665.60}},
					"memory": {"memfree": 8229844, "memused": 4051284, "memused-percent": 32.99, "buffers": 125564, "cached": 1537664, "commit": 8045848, "commit-percent": 36.50, "active": 2831940, "inactive": 891328, "dirty": 3596, "anonpg": 2060136, "slab": 143912, "kstack": 10096, "pgtbl": 47916, "vmused": 138332, "swpfree": 9764860, "swpused": 0, "swpused-percent": 0.00, "swpcad": 0, "swpcad-percent": 0.00, "frmpg": 173.86, "bufpg": 0.73, "campg": 1.16},
					"hugepages": {"hugfree": 0, "hugused": 0, "hugused-percent": 0.00},
					"kernel": {"dentunusd": 87474, "file-nr": 7712, "inode-nr": 63410, "pty-nr": 16},
					"queue": {"runq-sz": 0, "plist-sz": 631, "ldavg-1": 1.63, "ldavg-5": 1.77, "ldavg-15": 1.13, "blocked": 0},
					"serial": [
						{"line": 0, "rcvin": 0.00, "xmtin": 0.00, "framerr": 0.00, "prtyerr": 0.00, "brk": 0.00, "ovrun": 0.00}
					],
					"disk": [
						{"disk-device": "dev8-0", "tps": 4.92, "rd_sec": 2.43, "wr_sec": 665.60, "avgrq-sz": 135.78, "avgqu-sz": 0.01, "await": 1.76, "svctm": 0.39, "util-percent": 0.19},
						{"disk-device": "dev8-16", "tps": 0.00, "rd_sec": 0.00, "wr_sec": 0.00, "avgrq-sz": 0.00, "avgqu-sz": 0.00, "await": 0.00, "svctm": 0.00, "util-percent": 0.00},
						{"disk-device": "dev8-32", "tps": 0.00, "rd_sec": 0.00, "wr_sec": 0.00, "avgrq-sz": 0.00, "avgqu-sz": 0.00, "await": 0.00, "svctm": 0.00, "util-percent": 0.00}
					],
					"network": {
						"net-dev": [
							{"iface": "enp7s0", "rxpck": 176.31, "txpck": 91.44, "rxkB": 255.66, "txkB": 6.47, "rxcmp": 0.00, "txcmp": 0.00, "rxmcst": 0.00, "ifutil-percent": 2.09},
							{"iface": "lo", "rxpck": 0.22, "txpck": 0.22, "rxkB": 0.02, "txkB": 0.02, "rxcmp": 0.00, "txcmp": 0.00, "rxmcst": 0.00, "ifutil-percent": 0.00}
						],
						"net-edev": [
							{"iface": "enp7s0", "rxerr": 0.00, "txerr": 0.00, "coll": 0.00, "rxdrop": 0.00, "txdrop": 0.00, "txcarr": 0.00, "rxfram": 0.00, "rxfifo": 0.00, "txfifo": 0.00},
							{"iface": "lo", "rxerr": 0.00, "txerr": 0.00, "coll": 0.00, "rxdrop": 0.00, "txdrop": 0.00, "txcarr": 0.00, "rxfram": 0.00, "rxfifo": 0.00, "txfifo": 0.00}
						],
						"net-nfs": {"call": 0.00, "retrans": 0.00, "read": 0.00, "write": 0.00, "access": 0.00, "getatt": 0.00},
						"net-nfsd": {"scall": 0.00, "badcall": 0.00, "packet": 0.00, "udp": 0.00, "tcp": 0.00, "hit": 0.00, "miss": 0.00, "sread": 0.00, "swrite": 0.00, "saccess": 0.00, "sgetatt": 0.00},
						"net-sock": {"totsck": 947, "tcpsck": 21, "udpsck": 7, "rawsck": 0, "ip-frag": 0, "tcp-tw": 1}		
    // Should have comma here			
    "fchosts": [

					]
				}

**Comment by grogancolin** [comment]
Have done more investigation on this.

It seems to have been introduced in v11.1.5 (I compiled all the versions available github and checked from 11.2 back).

**Comment by sysstat** [comment]
In fact, this is because the fchost entry should not be displayed when no statistics data exist for Fibre Channel. Commit 54b03d1 should fix this.
Thanks.

**Comment by grogancolin** [comment]
That fixes it for me.

Thanks for the v quick response!
