### ISSUE TITLE
Allow wider Device: column when using  iostat -N 

### ISSUE THREAD

**Issue by ghost** [sysstat/sysstat#91]
Great output for LVM users is hardly readable when LV/VG names are long :(
Detect terminal width or allow to provide column size as option?

Example:
Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00    38.93    0.30  157.30     0.02     5.26    68.60     6.90   43.80   38.22   43.81   4.94  77.81
sdb               0.00    39.33    0.60  156.87     0.03     5.26    68.71     6.93   44.00   25.39   44.08   4.28  67.47
sdc               0.17     0.43  246.77  189.33     6.07     5.01    52.02     0.33    0.76    0.87    0.62   0.15   6.69
md5               0.00     0.00    0.33    0.33     0.02     0.00    60.40     0.00    0.00    0.00    0.00   0.00   0.00
md9               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vg_raid10_bitmap-root     0.00     0.00    0.33    0.27     0.02     0.00    67.11     0.06   93.50   53.30  143.75  46.11   2.77
vg_raid10_bitmap-host7_backup     0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
md3               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
md8               0.00     0.00    0.10   29.30     0.00     0.26    18.56     0.00    0.00    0.00    0.00   0.00   0.00
md10              0.00     0.00    0.47  162.17     0.03     4.99    63.17     0.00    0.00    0.00    0.00   0.00   0.00
vg_raid10_dmcache-foo_pl_postgresql     0.00     0.00  246.77  161.10     6.06     4.98    55.48    36.51   89.51    0.89  225.26   2.09  85.44
vg_raid10_dmcache-foo_main_postgresql_cachepool_cdata     0.00     0.00    0.17   29.33     0.00     0.27    18.71     0.00    0.12    0.00    0.12   0.08   0.25
vg_raid10_dmcache-foo_main_postgresql_cachepool_cmeta     0.00     0.00    0.00    0.53     0.00     0.00     6.00     0.00    0.00    0.00    0.00   0.00   0.00
vg_raid10_dmcache-foo_main_postgresql_corig     0.00     0.00    0.10   29.30     0.00     0.26    18.56     7.79  264.87   41.33  265.63  12.63  37.12
vg_raid10_dmcache-foo_main_postgresql     0.00     0.00    0.23   29.10     0.00     0.26    18.74     7.79  265.61   17.71  267.60  12.65  37.12
vg_raid10_dmcache-foocass1_cachepool_cdata     0.00     0.00    0.00    0.80     0.00     0.00     7.00     0.00    0.58    0.00    0.58   0.42   0.03
vg_raid10_dmcache-foocass1_cachepool_cmeta     0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vg_raid10_dmcache-foocass1_corig     0.00     0.00    0.00    0.87     0.00     0.00     7.08     0.10  119.46    0.00  119.46  80.12   6.94
vg_raid10_dmcache-foocass1     0.00     0.00    0.00    0.77     0.00     0.00     8.00     0.10  135.65    0.00  135.65  91.00   6.98
vg_raid10_dmcache-foo_pl_postgresql_cachepool_cdata     0.00     0.00  246.77  155.37     6.06     4.73    54.96     0.33    0.83    0.88    0.74   0.16   6.52
vg_raid10_dmcache-foo_pl_postgresql_cachepool_cmeta     0.00     0.00    0.00    3.73     0.00     0.01     6.00     0.00    0.04    0.00    0.04   0.03   0.01
vg_raid10_dmcache-foo_pl_postgresql_corig     0.00     0.00    0.47  161.30     0.03     4.98    63.47    35.95  222.23   10.21  222.84   5.22  84.42

**Comment by sysstat** [comment]
Try to also use iostat's option -h, which was added to make output easier to read.
